In [ ]:
#info,index,column,rename,axis,astype,concate,condition,ignor_index,random row-column, shape[]
#replace with nun-non-null value, head(), tail(), fillna(), dropna(), drop, inplace(), max
#min,mean, quantile, median

In [ ]:
import pandas as pd
import numpy as np
Dataset1 = pd.read_csv('insurance (1).csv')
print(Dataset1)

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [3]:
print(Dataset1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB
None


In [5]:
print(Dataset1.dtypes)

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object


In [10]:
alldata = pd.DataFrame(Dataset1, index=[60,70,80,90])
print(alldata)

    age     sex     bmi  children smoker     region      charges
60   43    male  27.360         3     no  northeast   8606.21740
70   27  female  24.750         0    yes  southeast  16577.77950
80   31    male  26.885         1     no  northeast   4441.21315
90   21  female  39.490         0     no  southeast   2026.97410


In [21]:
#alldata = pd.DataFrame(Dataset1, index=[41:51])
#print(alldata)                                         don't do this

In [13]:
print(Dataset1.head())

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520


In [14]:
print(Dataset1.head(3))

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620


In [15]:
print(Dataset1.tail())

      age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603


In [17]:
print(Dataset1.tail(4))

      age     sex    bmi  children smoker     region     charges
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603


In [19]:
print(Dataset1[101:201])

     age     sex     bmi  children smoker     region      charges
101   30    male  25.460         0     no  northeast   3645.08940
102   18  female  30.115         0     no  northeast  21344.84670
103   61  female  29.920         3    yes  southeast  30942.19180
104   34  female  27.500         1     no  southwest   5003.85300
105   20    male  28.025         1    yes  northwest  17560.37975
..   ...     ...     ...       ...    ...        ...          ...
196   39  female  32.800         0     no  southwest   5649.71500
197   45  female  28.600         2     no  southeast   8516.82900
198   51  female  18.050         0     no  northwest   9644.25250
199   64  female  39.330         0     no  northeast  14901.51670
200   19  female  32.110         0     no  northwest   2130.67590

[100 rows x 7 columns]


In [27]:
#column Rename
#Dataset1.rename(columns=['Age','Sex','Bmi','Children','Smoker','Region','Charges'], inplace=True) X Don't
Dataset1.rename({'age':'Age','sex':'Sex','bmi':'Bmi','children':'Children','smoker':'Smoker','region':'Region','charges':'Charges'}, axis=1, inplace=True)
print(Dataset1)

      Age     Sex     Bmi  Children Smoker     Region      Charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [31]:
#new_dataset = pd.DataFrame(Dataset1, columns=['AGE','SEX','BMI','CHILDREN','SMOKER','REGION','CHARGES'])
#print(new_dataset) x DON'T

In [37]:
Dataset1['Region'][61:71]

61    southeast
62    northwest
63    northwest
64    northwest
65    southwest
66    southwest
67    northwest
68    southeast
69    southeast
70    southeast
Name: Region, dtype: object

In [38]:
Dataset1['Age'] = Dataset1['Age'].astype(str, errors='ignore')
print(Dataset1)

     Age     Sex     Bmi  Children Smoker     Region      Charges
0     19  female  27.900         0    yes  southwest  16884.92400
1     18    male  33.770         1     no  southeast   1725.55230
2     28    male  33.000         3     no  southeast   4449.46200
3     33    male  22.705         0     no  northwest  21984.47061
4     32    male  28.880         0     no  northwest   3866.85520
...   ..     ...     ...       ...    ...        ...          ...
1333  50    male  30.970         3     no  northwest  10600.54830
1334  18  female  31.920         0     no  northeast   2205.98080
1335  18  female  36.850         0     no  southeast   1629.83350
1336  21  female  25.800         0     no  southwest   2007.94500
1337  61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [39]:
print(Dataset1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       1338 non-null   object 
 1   Sex       1338 non-null   object 
 2   Bmi       1338 non-null   float64
 3   Children  1338 non-null   int64  
 4   Smoker    1338 non-null   object 
 5   Region    1338 non-null   object 
 6   Charges   1338 non-null   float64
dtypes: float64(2), int64(1), object(4)
memory usage: 73.3+ KB
None


In [42]:
Dataset1['Age'] = Dataset1['Age'].astype(int, errors='ignore')
print(Dataset1)

      Age     Sex     Bmi  Children Smoker     Region      Charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [44]:
print(Dataset1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       1338 non-null   int64  
 1   Sex       1338 non-null   object 
 2   Bmi       1338 non-null   float64
 3   Children  1338 non-null   int64  
 4   Smoker    1338 non-null   object 
 5   Region    1338 non-null   object 
 6   Charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB
None


In [46]:
Dataset1['Bmi'] = Dataset1['Bmi'].astype(int, errors='ignore')
print(Dataset1)

      Age     Sex  Bmi  Children Smoker     Region      Charges
0      19  female   27         0    yes  southwest  16884.92400
1      18    male   33         1     no  southeast   1725.55230
2      28    male   33         3     no  southeast   4449.46200
3      33    male   22         0     no  northwest  21984.47061
4      32    male   28         0     no  northwest   3866.85520
...   ...     ...  ...       ...    ...        ...          ...
1333   50    male   30         3     no  northwest  10600.54830
1334   18  female   31         0     no  northeast   2205.98080
1335   18  female   36         0     no  southeast   1629.83350
1336   21  female   25         0     no  southwest   2007.94500
1337   61  female   29         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [49]:
Dataset1['Bmi'] = Dataset1['Bmi'].astype(float, errors='ignore')
print(Dataset1)

      Age     Sex   Bmi  Children Smoker     Region      Charges
0      19  female  27.0         0    yes  southwest  16884.92400
1      18    male  33.0         1     no  southeast   1725.55230
2      28    male  33.0         3     no  southeast   4449.46200
3      33    male  22.0         0     no  northwest  21984.47061
4      32    male  28.0         0     no  northwest   3866.85520
...   ...     ...   ...       ...    ...        ...          ...
1333   50    male  30.0         3     no  northwest  10600.54830
1334   18  female  31.0         0     no  northeast   2205.98080
1335   18  female  36.0         0     no  southeast   1629.83350
1336   21  female  25.0         0     no  southwest   2007.94500
1337   61  female  29.0         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [52]:
Dataset1['Sex'] = Dataset1['Sex'].astype('category')
print(Dataset1)

      Age     Sex   Bmi  Children Smoker     Region      Charges
0      19  female  27.0         0    yes  southwest  16884.92400
1      18    male  33.0         1     no  southeast   1725.55230
2      28    male  33.0         3     no  southeast   4449.46200
3      33    male  22.0         0     no  northwest  21984.47061
4      32    male  28.0         0     no  northwest   3866.85520
...   ...     ...   ...       ...    ...        ...          ...
1333   50    male  30.0         3     no  northwest  10600.54830
1334   18  female  31.0         0     no  northeast   2205.98080
1335   18  female  36.0         0     no  southeast   1629.83350
1336   21  female  25.0         0     no  southwest   2007.94500
1337   61  female  29.0         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [53]:
print(Dataset1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype   
---  ------    --------------  -----   
 0   Age       1338 non-null   int64   
 1   Sex       1338 non-null   category
 2   Bmi       1338 non-null   float64 
 3   Children  1338 non-null   int64   
 4   Smoker    1338 non-null   object  
 5   Region    1338 non-null   object  
 6   Charges   1338 non-null   float64 
dtypes: category(1), float64(2), int64(2), object(2)
memory usage: 64.3+ KB
None


In [58]:
Dataset1['Sex'] = Dataset1['Sex'].astype(str, errors='ignore')
print(Dataset1)

      Age     Sex   Bmi  Children Smoker     Region      Charges
0      19  female  27.0         0    yes  southwest  16884.92400
1      18    male  33.0         1     no  southeast   1725.55230
2      28    male  33.0         3     no  southeast   4449.46200
3      33    male  22.0         0     no  northwest  21984.47061
4      32    male  28.0         0     no  northwest   3866.85520
...   ...     ...   ...       ...    ...        ...          ...
1333   50    male  30.0         3     no  northwest  10600.54830
1334   18  female  31.0         0     no  northeast   2205.98080
1335   18  female  36.0         0     no  southeast   1629.83350
1336   21  female  25.0         0     no  southwest   2007.94500
1337   61  female  29.0         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [59]:
print(Dataset1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       1338 non-null   int64  
 1   Sex       1338 non-null   object 
 2   Bmi       1338 non-null   object 
 3   Children  1338 non-null   int64  
 4   Smoker    1338 non-null   object 
 5   Region    1338 non-null   object 
 6   Charges   1338 non-null   float64
dtypes: float64(1), int64(2), object(4)
memory usage: 73.3+ KB
None


In [71]:
top = Dataset1.head()
bottom = Dataset1.tail()
random = Dataset1[601:606]
a_new_datset = pd.concat([top,bottom,random], ignore_index=True)
print(a_new_datset)

    Age     Sex   Bmi  Children Smoker     Region      Charges
0    19  female  27.0         0    yes  southwest  16884.92400
1    18    male  33.0         1     no  southeast   1725.55230
2    28    male  33.0         3     no  southeast   4449.46200
3    33    male  22.0         0     no  northwest  21984.47061
4    32    male  28.0         0     no  northwest   3866.85520
5    50    male  30.0         3     no  northwest  10600.54830
6    18  female  31.0         0     no  northeast   2205.98080
7    18  female  36.0         0     no  southeast   1629.83350
8    21  female  25.0         0     no  southwest   2007.94500
9    61  female  29.0         0    yes  northwest  29141.36030
10   51    male  31.0         0     no  northwest   9174.13565
11   56  female  25.0         0     no  southwest  11070.53500
12   64  female  39.0         3     no  southeast  16085.12750
13   19  female  28.0         0    yes  northwest  17468.98390
14   51  female  34.0         0     no  southeast   928

In [98]:
change_bottom = Dataset1.tail(2).rename(columns={
    'Age':'AGE',
    'Sex':'SEX',
    'Bmi':'BMI',
    'Children':'CHILDREN',
    'Smoker':'SMOKER',
    'Region':'REGION',
    'Charges':'CHARGES'
    })
change_bottom = change_bottom.reset_index(drop=True)
change_top = Dataset1.head(2)
change_top = change_top.reset_index(drop=True)
change_center = Dataset1[1001:1003].rename(columns={
    'Age':'AGE',
    'Sex':'SEX',
    'Bmi':'BMI',
    'Children':'CHILDREN',
    'Smoker':'SMOKER',
    'Region':'REGION',
})
change_center = change_center.reset_index(drop=True)
b_new_set = pd.concat([change_bottom, change_top, change_center], axis=1)
print(b_new_set)

   AGE     SEX   BMI CHILDREN  SMOKER     REGION     CHARGES  Age     Sex  \
0   21  female  25.0        0      no  southwest   2007.9450   19  female   
1   61  female  29.0        0     yes  northwest  29141.3603   18    male   

    Bmi  ...  Smoker     Region     Charges  AGE   SEX   BMI CHILDREN  SMOKER  \
0  27.0  ...     yes  southwest  16884.9240   24  male  32.0        0     yes   
1  33.0  ...      no  southeast   1725.5523   24  male  25.0        0      no   

      REGION    Charges  
0  southwest  34472.841  
1  southwest   1972.950  

[2 rows x 21 columns]


In [118]:
import numpy as np
randomly = np.random.rand(10,6)
for i in randomly:
    print(i)

[0.62040284 0.05278726 0.86132424 0.68709341 0.97339331 0.44492916]
[0.46439296 0.48965836 0.80759469 0.2464903  0.3570155  0.38935673]
[0.04614562 0.44155    0.38865506 0.62067726 0.59406436 0.30546865]
[0.80570754 0.64155341 0.82853014 0.39804561 0.56884416 0.57562735]
[0.63201985 0.10069824 0.97512769 0.5732244  0.20947819 0.73648514]
[0.67357974 0.55345608 0.03787346 0.73799626 0.78475606 0.10372039]
[0.32824028 0.91821526 0.64568558 0.18184356 0.58670849 0.26475222]
[0.18456331 0.48752525 0.86883423 0.22247543 0.10580077 0.06373641]
[0.73618246 0.40809438 0.72903571 0.56166553 0.61513178 0.4561588 ]
[0.33618287 0.25596955 0.28450525 0.94424472 0.2313925  0.39611896]


In [116]:
import numpy as np
randomly = np.random.rand(10,6)
for i in range(randomly.shape[1]):
    nan_value = np.random.choice(5,3, replace=False)
    randomly[nan_value, i] = np.nan
    random_dar = pd.DataFrame(randomly)
print(randomly)

[[       nan 0.54406785 0.0667271         nan        nan 0.63818353]
 [       nan        nan        nan 0.54065666 0.00187958        nan]
 [0.40306303 0.81032298 0.33790362        nan 0.66705056 0.38746818]
 [       nan        nan        nan        nan        nan        nan]
 [0.7494024         nan        nan 0.89765393        nan        nan]
 [0.6474568  0.34735674 0.02524354 0.35971136 0.31278315 0.23692904]
 [0.85798906 0.83007208 0.84724768 0.14109607 0.21806574 0.83121413]
 [0.27591397 0.05173107 0.43554831 0.40744344 0.09044548 0.23936332]
 [0.21410016 0.25626438 0.77082869 0.10118125 0.78168776 0.24211499]
 [0.77243073 0.04867755 0.52543578 0.52956195 0.83502625 0.23456965]]
