In [4]:
import pandas as pd
a = [3,5,7]
df = pd.Series(a)
df

0    3
1    5
2    7
dtype: int64

In [5]:
df.info()

<class 'pandas.core.series.Series'>
RangeIndex: 3 entries, 0 to 2
Series name: None
Non-Null Count  Dtype
--------------  -----
3 non-null      int64
dtypes: int64(1)
memory usage: 156.0 bytes


In [6]:
a = (3,5,7)
df = pd.Series(a)
df

0    3
1    5
2    7
dtype: int64

In [ ]:
dic = {
    'Name':['Maruf', 'Jidni'],
    'Roll': [884598, 884588]
    }
df = pd.Series(dic)
df

Name      [Maruf, Jidni]
Roll    [884598, 884588]
dtype: object

In [13]:
df.info()

<class 'pandas.core.series.Series'>
Index: 2 entries, Name to Roll
Series name: None
Non-Null Count  Dtype 
--------------  ----- 
2 non-null      object
dtypes: object(1)
memory usage: 140.0+ bytes


In [18]:
dic = {
    'Name' : ['Maruf', 'Rajin', 'Jidni'],
    'Roll' : [23, 56, 21],
    'dep' : ['cst', 'auto', 'cst']
}
df = pd.Series(dic, index=['Name', 'Roll', 'dep'])
df

Name    [Maruf, Rajin, Jidni]
Roll             [23, 56, 21]
dep          [cst, auto, cst]
dtype: object

In [19]:
df.info()

<class 'pandas.core.series.Series'>
Index: 3 entries, Name to dep
Series name: None
Non-Null Count  Dtype 
--------------  ----- 
3 non-null      object
dtypes: object(1)
memory usage: 156.0+ bytes


In [31]:
a = [[3,5,7]]
df = pd.DataFrame(a)
df


0  1  2
0  3  5  7

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       1 non-null      int64
 1   1       1 non-null      int64
 2   2       1 non-null      int64
dtypes: int64(3)
memory usage: 156.0 bytes


In [26]:
b = [3,5,7]
df2 = pd.DataFrame(b)
df2

0
0  3
1  5
2  7

In [28]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       3 non-null      int64
dtypes: int64(1)
memory usage: 156.0 bytes


In [32]:
a = [[3,5,7]]
df = pd.DataFrame(a, columns=['N1', 'N2', 'N3'])
df

N1  N2  N3
0   3   5   7

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   N1      1 non-null      int64
 1   N2      1 non-null      int64
 2   N3      1 non-null      int64
dtypes: int64(3)
memory usage: 156.0 bytes


In [38]:
b = [3,5,7]
df2 = pd.DataFrame(b, columns=['Rolls'])
df2

Rolls
0      3
1      5
2      7

In [36]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       3 non-null      int64
dtypes: int64(1)
memory usage: 156.0 bytes


In [50]:
b = [['maruf', 'jidni', 'rajin'],[3,5,7]]
df2 = pd.DataFrame(b)
df2

0      1      2
0  maruf  jidni  rajin
1      3      5      7

In [41]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       2 non-null      object
 1   1       2 non-null      object
 2   2       2 non-null      object
dtypes: object(3)
memory usage: 180.0+ bytes


In [45]:
b = [['maruf', 'jidni', 'rajin'],[3,5,7]]
df2 = pd.DataFrame(b, columns= ['col1', 'col2', 'col3'])
df2

col1   col2   col3
0  maruf  jidni  rajin
1      3      5      7

In [46]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   col1    2 non-null      object
 1   col2    2 non-null      object
 2   col3    2 non-null      object
dtypes: object(3)
memory usage: 180.0+ bytes


In [54]:
dic = {
    'Name' : ['Maruf', 'Rajin', 'Jidni', 'robin'],
    'Roll' : [23, 56, 21, 56],
    'dep' : ['cst', 'auto', 'cst', 'Et']
}
df = pd.DataFrame(dic)
df

Name  Roll   dep
0  Maruf    23   cst
1  Rajin    56  auto
2  Jidni    21   cst
3  robin    56    Et

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Roll    4 non-null      int64 
 2   dep     4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes


In [ ]:
dic = {
    'Name' : ['Maruf', 'Rajin', 'Jidni', 'robin'],
    'Roll' : [23, 56, 21, 56],
    'dep' : ['cst', 'auto', 'cst', 'Et']
}
df = pd.DataFrame(dic)
#df = pd.DataFrame(dic, columns=['NAME','ROLL', 'DEP']) don't change like this
df

Name  Roll   dep
0  Maruf    23   cst
1  Rajin    56  auto
2  Jidni    21   cst
3  robin    56    Et

In [59]:
df = df.rename({'Name':'নাম', 'Roll':'রোল', 'dep':'ডিপারট্মেন্ট'}, axis=1)
df

নাম  রোল ডিপারট্মেন্ট
0  Maruf   23          cst
1  Rajin   56         auto
2  Jidni   21          cst
3  robin   56           Et

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   নাম           4 non-null      object
 1   রোল           4 non-null      int64 
 2   ডিপারট্মেন্ট  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 128.0+ bytes


In [65]:
dic = {
    'Name' : ['Maruf', 'Rajin', 'Jidni', 'robin'],
    'Roll' : [23, 56, 21, 56],
    'dep' : ['cst', 'auto', 'cst', 'Et']
}
df = pd.DataFrame(dic)
df

Name  Roll   dep
0  Maruf    23   cst
1  Rajin    56  auto
2  Jidni    21   cst
3  robin    56    Et

In [67]:
df['Roll']

0    23
1    56
2    21
3    56
Name: Roll, dtype: int64

In [70]:
df[['Roll']]

Roll
0    23
1    56
2    21
3    56

In [71]:
df[['Name']]

Name
0  Maruf
1  Rajin
2  Jidni
3  robin

In [72]:
df[['dep']]

dep
0   cst
1  auto
2   cst
3    Et

In [74]:
dic = {
    'Name' : ['Maruf', 'Rajin', 'Jidni', 'robin'],
    'Roll' : [2354367467, 564567756, 214567567, 56567457],
    'dep' : ['cst', 'auto', 'cst', 'Et']
}
df = pd.DataFrame(dic)
df

Name        Roll   dep
0  Maruf  2354367467   cst
1  Rajin   564567756  auto
2  Jidni   214567567   cst
3  robin    56567457    Et

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Roll    4 non-null      int64 
 2   dep     4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes


In [81]:
df[['Roll']].astype('int64')

Roll
0  2354367467
1   564567756
2   214567567
3    56567457

In [83]:
df[['Roll']].astype('int32')

Roll
0 -1940599829
1   564567756
2   214567567
3    56567457

In [84]:
df[['Roll']].astype('int16')

Roll
0 -13333
1 -24884
2   2703
3   9889

In [85]:
dic = {
    'Name' : ['Maruf', 'Rajin', 'Jidni', 'robin'],
    'Roll' : [230, 560, 210, 500],
    'dep' : ['cst', 'auto', 'cst', 'Et']
}
df = pd.DataFrame(dic)
df

Name  Roll   dep
0  Maruf   230   cst
1  Rajin   560  auto
2  Jidni   210   cst
3  robin   500    Et

In [89]:
df['Roll']>300 # can't use 2 dimesional array

0    False
1     True
2    False
3     True
Name: Roll, dtype: bool

In [92]:
df[df['Roll']>300]

Name  Roll   dep
1  Rajin   560  auto
3  robin   500    Et

In [93]:
df[df['Roll']>300]['Name']

1    Rajin
3    robin
Name: Name, dtype: object

In [100]:
dic1 = {
    'Name' : ['Maruf', 'Rajin', 'Jidni', 'robin'],
    'Roll' : [230, 560, 210, 500],
    'Dep' : ['cst', 'auto', 'cst', 'Et']
}
df3 = pd.DataFrame(dic)
df3

Name  Roll   dep
0  Maruf   230   cst
1  Rajin   560  auto
2  Jidni   210   cst
3  robin   500    Et

In [101]:
dic2 = {
    'name':['nibir','alimoon','sameer','aryan'],
    'roll':[435,65,5,67],
    'dep':['mec','sc','auto','cst']

}
df4 = pd.DataFrame(dic2)
print(df4)

      name  roll   dep
0    nibir   435   mec
1  alimoon    65    sc
2   sameer     5  auto
3    aryan    67   cst


In [104]:
new_dic = pd.concat([df3,df4])
print(new_dic)

    Name   Roll   dep     name   roll
0  Maruf  230.0   cst      NaN    NaN
1  Rajin  560.0  auto      NaN    NaN
2  Jidni  210.0   cst      NaN    NaN
3  robin  500.0    Et      NaN    NaN
0    NaN    NaN   mec    nibir  435.0
1    NaN    NaN    sc  alimoon   65.0
2    NaN    NaN  auto   sameer    5.0
3    NaN    NaN   cst    aryan   67.0


In [106]:
new_dic = pd.concat([df3,df4], axis=1)
print(new_dic)

    Name  Roll   dep     name  roll   dep
0  Maruf   230   cst    nibir   435   mec
1  Rajin   560  auto  alimoon    65    sc
2  Jidni   210   cst   sameer     5  auto
3  robin   500    Et    aryan    67   cst


In [115]:
dic1 = {
    'Name' : ['Maruf', 'Rajin', 'Jidni', 'robin'],
    'Roll' : [230, 560, 210, 500],
    'Dep' : ['cst', 'auto', 'cst', 'Et']
}
df3 = pd.DataFrame(dic1)
df3

Name  Roll   Dep
0  Maruf   230   cst
1  Rajin   560  auto
2  Jidni   210   cst
3  robin   500    Et

In [113]:
dic2 = {
    'Name':['nibir','alimoon','sameer','aryan'],
    'Roll':[435,65,5,67],
    'Dep':['mec','sc','auto','cst']

}
df4 = pd.DataFrame(dic2)
print(df4)

      Name  Roll   Dep
0    nibir   435   mec
1  alimoon    65    sc
2   sameer     5  auto
3    aryan    67   cst


In [116]:
new_dic2 = pd.concat([df3,df4])
print(new_dic2)

      Name  Roll   Dep
0    Maruf   230   cst
1    Rajin   560  auto
2    Jidni   210   cst
3    robin   500    Et
0    nibir   435   mec
1  alimoon    65    sc
2   sameer     5  auto
3    aryan    67   cst


In [117]:
new_dic2 = pd.concat([df3,df4], ignore_index=True)
print(new_dic2)

      Name  Roll   Dep
0    Maruf   230   cst
1    Rajin   560  auto
2    Jidni   210   cst
3    robin   500    Et
4    nibir   435   mec
5  alimoon    65    sc
6   sameer     5  auto
7    aryan    67   cst


In [120]:
import numpy as np
data = np.random.rand(10,5)
print(data)

[[0.30811919 0.99285116 0.95646887 0.10477275 0.04463709]
 [0.66866681 0.29413653 0.35907449 0.82600087 0.39645553]
 [0.43154484 0.2176686  0.88444627 0.93482596 0.31577976]
 [0.35434311 0.62279777 0.69762564 0.97737693 0.37674516]
 [0.65921608 0.57315556 0.91229736 0.965634   0.24095254]
 [0.95280931 0.20968364 0.1031416  0.65845113 0.83746602]
 [0.55379773 0.29120523 0.37644402 0.18026444 0.9138162 ]
 [0.98363647 0.85834018 0.01013491 0.96513293 0.01705273]
 [0.65020876 0.22145084 0.90288327 0.59503862 0.03656721]
 [0.69473499 0.37668486 0.93874492 0.98983777 0.8826212 ]]


In [122]:
data = np.random.rand(10,5)
for x in data:
    print(x)

[0.2329046  0.71164058 0.89737341 0.14272985 0.56484852]
[0.08775462 0.27958273 0.46572533 0.9236855  0.03108869]
[0.99332306 0.96198944 0.32614333 0.65132847 0.91414647]
[0.35936406 0.26440382 0.34143749 0.43563402 0.46677923]
[0.48164564 0.10469323 0.61356482 0.75659758 0.80419393]
[0.04498866 0.93655952 0.39461489 0.06648538 0.62272337]
[0.88715298 0.78140119 0.14341764 0.06175053 0.15984595]
[0.2242978  0.17251653 0.23095747 0.25088656 0.12205014]
[0.87966799 0.71068088 0.25450018 0.03529956 0.16338991]
[0.22061589 0.215305   0.56587393 0.03328683 0.71296935]


In [2]:
import numpy as np
data = np.random.rand(10,5)
for x in range(data.shape[1]):
    print(x)

0
1
2
3
4


In [17]:
import numpy as np
import pandas as pd
data = np.random.rand(10,5)
for x in range(data.shape[1]):
    nan_value = np.random.choice(6,4, replace=False)
    data[nan_value, x] = np.nan
    daf = pd.DataFrame(data)
print(daf)

          0         1         2         3         4
0  0.965033       NaN       NaN       NaN  0.304996
1       NaN       NaN       NaN       NaN       NaN
2       NaN  0.440526       NaN  0.466514       NaN
3       NaN       NaN  0.220013  0.676454       NaN
4       NaN       NaN       NaN       NaN  0.390046
5  0.825963  0.252814  0.916089       NaN       NaN
6  0.441491  0.914045  0.485289  0.945844  0.583843
7  0.126204  0.338109  0.594286  0.998447  0.250549
8  0.811040  0.076154  0.625736  0.662709  0.533222
9  0.308857  0.751008  0.886644  0.843958  0.495046


In [30]:
print(daf.head())

          0         1         2         3         4
0  0.965033       NaN       NaN       NaN  0.304996
1       NaN       NaN       NaN       NaN       NaN
2       NaN  0.440526       NaN  0.466514       NaN
3       NaN       NaN  0.220013  0.676454       NaN
4       NaN       NaN       NaN       NaN  0.390046


In [31]:
print(daf.head(3))

          0         1   2         3         4
0  0.965033       NaN NaN       NaN  0.304996
1       NaN       NaN NaN       NaN       NaN
2       NaN  0.440526 NaN  0.466514       NaN


In [38]:
import numpy as np
import pandas as pd
data = np.random.rand(10,5)
for x in range(data.shape[1]):
    nan_value = np.random.choice(6,3, replace=False)
    data[nan_value, x] = np.nan
    daf = pd.DataFrame(data)
print(daf)

          0         1         2         3         4
0       NaN  0.880770       NaN       NaN  0.418406
1  0.032249       NaN       NaN  0.766325       NaN
2       NaN  0.316912  0.923455  0.650182       NaN
3  0.272869       NaN  0.272141  0.144242  0.004186
4       NaN  0.715416       NaN       NaN       NaN
5  0.360734       NaN  0.065420       NaN  0.268755
6  0.079400  0.626312  0.425440  0.961799  0.853566
7  0.986644  0.698572  0.319666  0.585658  0.478646
8  0.671531  0.240139  0.147347  0.997064  0.033232
9  0.500927  0.614739  0.989838  0.907353  0.164693


In [39]:
daf.columns=['col1','col2','col3','col4', 'col5']
print(daf)

       col1      col2      col3      col4      col5
0       NaN  0.880770       NaN       NaN  0.418406
1  0.032249       NaN       NaN  0.766325       NaN
2       NaN  0.316912  0.923455  0.650182       NaN
3  0.272869       NaN  0.272141  0.144242  0.004186
4       NaN  0.715416       NaN       NaN       NaN
5  0.360734       NaN  0.065420       NaN  0.268755
6  0.079400  0.626312  0.425440  0.961799  0.853566
7  0.986644  0.698572  0.319666  0.585658  0.478646
8  0.671531  0.240139  0.147347  0.997064  0.033232
9  0.500927  0.614739  0.989838  0.907353  0.164693


In [40]:
daf1 = daf.copy()
daf2 = daf.copy()
daf3 = daf.copy()
daf4 = daf.copy()

In [41]:
daf.dropna()

col1      col2      col3      col4      col5
6  0.079400  0.626312  0.425440  0.961799  0.853566
7  0.986644  0.698572  0.319666  0.585658  0.478646
8  0.671531  0.240139  0.147347  0.997064  0.033232
9  0.500927  0.614739  0.989838  0.907353  0.164693

In [42]:
daf = daf.dropna()
daf

col1      col2      col3      col4      col5
6  0.079400  0.626312  0.425440  0.961799  0.853566
7  0.986644  0.698572  0.319666  0.585658  0.478646
8  0.671531  0.240139  0.147347  0.997064  0.033232
9  0.500927  0.614739  0.989838  0.907353  0.164693

In [43]:
daf1 = daf1.drop(['col3'], axis=1)

In [44]:
daf2.drop(['col5'], axis=1, inplace=True)

In [45]:
daf2

col1      col2      col3      col4
0       NaN  0.880770       NaN       NaN
1  0.032249       NaN       NaN  0.766325
2       NaN  0.316912  0.923455  0.650182
3  0.272869       NaN  0.272141  0.144242
4       NaN  0.715416       NaN       NaN
5  0.360734       NaN  0.065420       NaN
6  0.079400  0.626312  0.425440  0.961799
7  0.986644  0.698572  0.319666  0.585658
8  0.671531  0.240139  0.147347  0.997064
9  0.500927  0.614739  0.989838  0.907353

In [46]:
daf2 = daf2.drop(['col1','col2'], axis=1)
daf2

col3      col4
0       NaN       NaN
1       NaN  0.766325
2  0.923455  0.650182
3  0.272141  0.144242
4       NaN       NaN
5  0.065420       NaN
6  0.425440  0.961799
7  0.319666  0.585658
8  0.147347  0.997064
9  0.989838  0.907353

In [47]:
print(daf3)

       col1      col2      col3      col4      col5
0       NaN  0.880770       NaN       NaN  0.418406
1  0.032249       NaN       NaN  0.766325       NaN
2       NaN  0.316912  0.923455  0.650182       NaN
3  0.272869       NaN  0.272141  0.144242  0.004186
4       NaN  0.715416       NaN       NaN       NaN
5  0.360734       NaN  0.065420       NaN  0.268755
6  0.079400  0.626312  0.425440  0.961799  0.853566
7  0.986644  0.698572  0.319666  0.585658  0.478646
8  0.671531  0.240139  0.147347  0.997064  0.033232
9  0.500927  0.614739  0.989838  0.907353  0.164693


In [50]:
daf3.fillna(4, inplace=True)
daf3

col1      col2      col3      col4      col5
0  4.000000  0.880770  4.000000  4.000000  0.418406
1  0.032249  4.000000  4.000000  0.766325  4.000000
2  4.000000  0.316912  0.923455  0.650182  4.000000
3  0.272869  4.000000  0.272141  0.144242  0.004186
4  4.000000  0.715416  4.000000  4.000000  4.000000
5  0.360734  4.000000  0.065420  4.000000  0.268755
6  0.079400  0.626312  0.425440  0.961799  0.853566
7  0.986644  0.698572  0.319666  0.585658  0.478646
8  0.671531  0.240139  0.147347  0.997064  0.033232
9  0.500927  0.614739  0.989838  0.907353  0.164693

In [51]:
daf4

col1      col2      col3      col4      col5
0       NaN  0.880770       NaN       NaN  0.418406
1  0.032249       NaN       NaN  0.766325       NaN
2       NaN  0.316912  0.923455  0.650182       NaN
3  0.272869       NaN  0.272141  0.144242  0.004186
4       NaN  0.715416       NaN       NaN       NaN
5  0.360734       NaN  0.065420       NaN  0.268755
6  0.079400  0.626312  0.425440  0.961799  0.853566
7  0.986644  0.698572  0.319666  0.585658  0.478646
8  0.671531  0.240139  0.147347  0.997064  0.033232
9  0.500927  0.614739  0.989838  0.907353  0.164693

In [52]:
daf4.describe()

col1      col2      col3      col4      col5
count  7.000000  7.000000  7.000000  7.000000  7.000000
mean   0.414908  0.584694  0.449044  0.716089  0.317355
std    0.337204  0.227588  0.366129  0.296308  0.296709
min    0.032249  0.240139  0.065420  0.144242  0.004186
25%    0.176134  0.465826  0.209744  0.617920  0.098962
50%    0.360734  0.626312  0.319666  0.766325  0.268755
75%    0.586229  0.706994  0.674447  0.934576  0.448526
max    0.986644  0.880770  0.989838  0.997064  0.853566

In [55]:
daf4['col1'].mean()

np.float64(0.41490761431950357)

In [56]:
daf4['col2'].median()

np.float64(0.6263119617448525)

In [57]:
daf4['col2'].max()

np.float64(0.880769823065273)

In [59]:
daf4['col2'].min()

np.float64(0.24013937378655215)

In [61]:
daf4['col2'].quantile(.25)

np.float64(0.46582575348608674)

In [62]:
daf4['col2'].quantile(.50)

np.float64(0.6263119617448525)