In [2]:
#info,index,column,rename,axis,astype,concate,condition,ignor_index,random row-column, shape[]
#replace with nun-non-null value, head(), tail(), fillna(), dropna(), drop, inplace(), max
#min,mean, quantile, median

In [72]:
import pandas as pd
import numpy as np
Dataset1 = pd.read_csv('insurance (1).csv')
print(Dataset1)


      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [76]:
Dataset_frame1 = Dataset1.copy()
Dataset_frame2 = Dataset1.copy()
Dataset_frame3 = Dataset1.copy()
Dataset_frame4 = Dataset1.copy()
Dataset_frame5 = Dataset1.copy()
Dataset_frame6 = Dataset1.copy()

In [4]:
print(Dataset1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB
None


In [5]:
print(Dataset1.dtypes)

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object


In [6]:
alldata = pd.DataFrame(Dataset1, index=[60,70,80,90])
print(alldata)

    age     sex     bmi  children smoker     region      charges
60   43    male  27.360         3     no  northeast   8606.21740
70   27  female  24.750         0    yes  southeast  16577.77950
80   31    male  26.885         1     no  northeast   4441.21315
90   21  female  39.490         0     no  southeast   2026.97410


In [7]:
#alldata = pd.DataFrame(Dataset1, index=[41:51])
#print(alldata)                                         don't do this

In [8]:
print(Dataset1.head())

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520


In [9]:
print(Dataset1.head(3))

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620


In [10]:
print(Dataset1.tail())

      age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603


In [11]:
print(Dataset1.tail(4))

      age     sex    bmi  children smoker     region     charges
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603


In [12]:
print(Dataset1[101:201])

     age     sex     bmi  children smoker     region      charges
101   30    male  25.460         0     no  northeast   3645.08940
102   18  female  30.115         0     no  northeast  21344.84670
103   61  female  29.920         3    yes  southeast  30942.19180
104   34  female  27.500         1     no  southwest   5003.85300
105   20    male  28.025         1    yes  northwest  17560.37975
..   ...     ...     ...       ...    ...        ...          ...
196   39  female  32.800         0     no  southwest   5649.71500
197   45  female  28.600         2     no  southeast   8516.82900
198   51  female  18.050         0     no  northwest   9644.25250
199   64  female  39.330         0     no  northeast  14901.51670
200   19  female  32.110         0     no  northwest   2130.67590

[100 rows x 7 columns]


In [13]:
#column Rename
#Dataset1.rename(columns=['Age','Sex','Bmi','Children','Smoker','Region','Charges'], inplace=True) X Don't
Dataset1.rename({'age':'Age','sex':'Sex','bmi':'Bmi','children':'Children','smoker':'Smoker','region':'Region','charges':'Charges'}, axis=1, inplace=True)
print(Dataset1)

      Age     Sex     Bmi  Children Smoker     Region      Charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [14]:
#new_dataset = pd.DataFrame(Dataset1, columns=['AGE','SEX','BMI','CHILDREN','SMOKER','REGION','CHARGES'])
#print(new_dataset) x DON'T

In [15]:
Dataset1['Region'][61:71]

61    southeast
62    northwest
63    northwest
64    northwest
65    southwest
66    southwest
67    northwest
68    southeast
69    southeast
70    southeast
Name: Region, dtype: object

In [16]:
Dataset1['Age'] = Dataset1['Age'].astype(str, errors='ignore')
print(Dataset1)

     Age     Sex     Bmi  Children Smoker     Region      Charges
0     19  female  27.900         0    yes  southwest  16884.92400
1     18    male  33.770         1     no  southeast   1725.55230
2     28    male  33.000         3     no  southeast   4449.46200
3     33    male  22.705         0     no  northwest  21984.47061
4     32    male  28.880         0     no  northwest   3866.85520
...   ..     ...     ...       ...    ...        ...          ...
1333  50    male  30.970         3     no  northwest  10600.54830
1334  18  female  31.920         0     no  northeast   2205.98080
1335  18  female  36.850         0     no  southeast   1629.83350
1336  21  female  25.800         0     no  southwest   2007.94500
1337  61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [17]:
print(Dataset1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       1338 non-null   object 
 1   Sex       1338 non-null   object 
 2   Bmi       1338 non-null   float64
 3   Children  1338 non-null   int64  
 4   Smoker    1338 non-null   object 
 5   Region    1338 non-null   object 
 6   Charges   1338 non-null   float64
dtypes: float64(2), int64(1), object(4)
memory usage: 73.3+ KB
None


In [18]:
Dataset1['Age'] = Dataset1['Age'].astype(int, errors='ignore')
print(Dataset1)

      Age     Sex     Bmi  Children Smoker     Region      Charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [19]:
print(Dataset1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       1338 non-null   int64  
 1   Sex       1338 non-null   object 
 2   Bmi       1338 non-null   float64
 3   Children  1338 non-null   int64  
 4   Smoker    1338 non-null   object 
 5   Region    1338 non-null   object 
 6   Charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB
None


In [20]:
Dataset1['Bmi'] = Dataset1['Bmi'].astype(int, errors='ignore')
print(Dataset1)

      Age     Sex  Bmi  Children Smoker     Region      Charges
0      19  female   27         0    yes  southwest  16884.92400
1      18    male   33         1     no  southeast   1725.55230
2      28    male   33         3     no  southeast   4449.46200
3      33    male   22         0     no  northwest  21984.47061
4      32    male   28         0     no  northwest   3866.85520
...   ...     ...  ...       ...    ...        ...          ...
1333   50    male   30         3     no  northwest  10600.54830
1334   18  female   31         0     no  northeast   2205.98080
1335   18  female   36         0     no  southeast   1629.83350
1336   21  female   25         0     no  southwest   2007.94500
1337   61  female   29         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [21]:
Dataset1['Bmi'] = Dataset1['Bmi'].astype(float, errors='ignore')
print(Dataset1)

      Age     Sex   Bmi  Children Smoker     Region      Charges
0      19  female  27.0         0    yes  southwest  16884.92400
1      18    male  33.0         1     no  southeast   1725.55230
2      28    male  33.0         3     no  southeast   4449.46200
3      33    male  22.0         0     no  northwest  21984.47061
4      32    male  28.0         0     no  northwest   3866.85520
...   ...     ...   ...       ...    ...        ...          ...
1333   50    male  30.0         3     no  northwest  10600.54830
1334   18  female  31.0         0     no  northeast   2205.98080
1335   18  female  36.0         0     no  southeast   1629.83350
1336   21  female  25.0         0     no  southwest   2007.94500
1337   61  female  29.0         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [22]:
Dataset1['Sex'] = Dataset1['Sex'].astype('category')
print(Dataset1)

      Age     Sex   Bmi  Children Smoker     Region      Charges
0      19  female  27.0         0    yes  southwest  16884.92400
1      18    male  33.0         1     no  southeast   1725.55230
2      28    male  33.0         3     no  southeast   4449.46200
3      33    male  22.0         0     no  northwest  21984.47061
4      32    male  28.0         0     no  northwest   3866.85520
...   ...     ...   ...       ...    ...        ...          ...
1333   50    male  30.0         3     no  northwest  10600.54830
1334   18  female  31.0         0     no  northeast   2205.98080
1335   18  female  36.0         0     no  southeast   1629.83350
1336   21  female  25.0         0     no  southwest   2007.94500
1337   61  female  29.0         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [23]:
print(Dataset1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype   
---  ------    --------------  -----   
 0   Age       1338 non-null   int64   
 1   Sex       1338 non-null   category
 2   Bmi       1338 non-null   float64 
 3   Children  1338 non-null   int64   
 4   Smoker    1338 non-null   object  
 5   Region    1338 non-null   object  
 6   Charges   1338 non-null   float64 
dtypes: category(1), float64(2), int64(2), object(2)
memory usage: 64.3+ KB
None


In [24]:
Dataset1['Sex'] = Dataset1['Sex'].astype(str, errors='ignore')
print(Dataset1)

      Age     Sex   Bmi  Children Smoker     Region      Charges
0      19  female  27.0         0    yes  southwest  16884.92400
1      18    male  33.0         1     no  southeast   1725.55230
2      28    male  33.0         3     no  southeast   4449.46200
3      33    male  22.0         0     no  northwest  21984.47061
4      32    male  28.0         0     no  northwest   3866.85520
...   ...     ...   ...       ...    ...        ...          ...
1333   50    male  30.0         3     no  northwest  10600.54830
1334   18  female  31.0         0     no  northeast   2205.98080
1335   18  female  36.0         0     no  southeast   1629.83350
1336   21  female  25.0         0     no  southwest   2007.94500
1337   61  female  29.0         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [25]:
print(Dataset1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       1338 non-null   int64  
 1   Sex       1338 non-null   object 
 2   Bmi       1338 non-null   float64
 3   Children  1338 non-null   int64  
 4   Smoker    1338 non-null   object 
 5   Region    1338 non-null   object 
 6   Charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB
None


In [26]:
top = Dataset1.head()
bottom = Dataset1.tail()
random = Dataset1[601:606]
a_new_datset = pd.concat([top,bottom,random], ignore_index=True)
print(a_new_datset)

    Age     Sex   Bmi  Children Smoker     Region      Charges
0    19  female  27.0         0    yes  southwest  16884.92400
1    18    male  33.0         1     no  southeast   1725.55230
2    28    male  33.0         3     no  southeast   4449.46200
3    33    male  22.0         0     no  northwest  21984.47061
4    32    male  28.0         0     no  northwest   3866.85520
5    50    male  30.0         3     no  northwest  10600.54830
6    18  female  31.0         0     no  northeast   2205.98080
7    18  female  36.0         0     no  southeast   1629.83350
8    21  female  25.0         0     no  southwest   2007.94500
9    61  female  29.0         0    yes  northwest  29141.36030
10   51    male  31.0         0     no  northwest   9174.13565
11   56  female  25.0         0     no  southwest  11070.53500
12   64  female  39.0         3     no  southeast  16085.12750
13   19  female  28.0         0    yes  northwest  17468.98390
14   51  female  34.0         0     no  southeast   928

In [27]:
change_bottom = Dataset1.tail(2).rename(columns={
    'Age':'AGE',
    'Sex':'SEX',
    'Bmi':'BMI',
    'Children':'CHILDREN',
    'Smoker':'SMOKER',
    'Region':'REGION',
    'Charges':'CHARGES'
    })
change_bottom = change_bottom.reset_index(drop=True)
change_top = Dataset1.head(2)
change_top = change_top.reset_index(drop=True)
change_center = Dataset1[1001:1003].rename(columns={
    'Age':'AGE',
    'Sex':'SEX',
    'Bmi':'BMI',
    'Children':'CHILDREN',
    'Smoker':'SMOKER',
    'Region':'REGION',
})
change_center = change_center.reset_index(drop=True)
b_new_set = pd.concat([change_bottom, change_top, change_center], axis=1)
print(b_new_set)

   AGE     SEX   BMI  CHILDREN  SMOKER     REGION     CHARGES  Age     Sex  \
0   21  female  25.0         0      no  southwest   2007.9450   19  female   
1   61  female  29.0         0     yes  northwest  29141.3603   18    male   

    Bmi  ...  Smoker     Region     Charges  AGE   SEX   BMI  CHILDREN  \
0  27.0  ...     yes  southwest  16884.9240   24  male  32.0         0   
1  33.0  ...      no  southeast   1725.5523   24  male  25.0         0   

   SMOKER     REGION    Charges  
0     yes  southwest  34472.841  
1      no  southwest   1972.950  

[2 rows x 21 columns]


In [28]:
import numpy as np
randomly = np.random.rand(10,6)
for i in randomly:
    print(i)

[0.93415082 0.42547008 0.86421288 0.6384032  0.27659025 0.64196871]
[0.00400197 0.49229939 0.37371877 0.94857497 0.06019534 0.73121246]
[0.14923778 0.05619785 0.83339548 0.07253461 0.41141136 0.55082874]
[0.24346362 0.69820499 0.10411604 0.81523027 0.84516443 0.88033402]
[0.32239862 0.29492049 0.62386758 0.78210724 0.09371014 0.96327713]
[0.11088648 0.22561716 0.82090016 0.03636063 0.7291353  0.86681383]
[0.87719301 0.14818838 0.64355696 0.22535875 0.30373984 0.98269677]
[0.31539767 0.52723632 0.7034082  0.67613822 0.21269341 0.44292529]
[2.41765988e-04 2.11766757e-01 7.50487594e-01 5.18609948e-01
 4.29472109e-01 2.11214303e-01]
[0.05709101 0.34802864 0.70769766 0.5016075  0.37722547 0.07255583]


In [29]:
import pandas as pd
import numpy as np
random_col = np.random.rand(10,6)
for i in range(random_col.shape[1]):
    nan_value = np.random.choice(5,3, replace=False)
    random_col[nan_value, i] = np.nan
    data_f = pd.DataFrame(random_col)
print(data_f)

          0         1         2         3         4         5
0  0.215622  0.637428       NaN       NaN       NaN  0.241125
1       NaN       NaN       NaN       NaN  0.419948  0.553259
2       NaN       NaN  0.154342  0.719951       NaN       NaN
3       NaN  0.969642  0.924289  0.213746       NaN       NaN
4  0.971079       NaN       NaN       NaN  0.320278       NaN
5  0.461919  0.448829  0.380253  0.722185  0.019304  0.538564
6  0.361488  0.635634  0.445780  0.920459  0.218627  0.305238
7  0.645114  0.172539  0.036665  0.119121  0.528304  0.714588
8  0.347043  0.218876  0.142018  0.368253  0.136960  0.044611
9  0.418439  0.334608  0.792867  0.396132  0.611818  0.741815


In [30]:
data_f.columns=['col1','col2','col3','col4','col5','col6']
print(data_f)

       col1      col2      col3      col4      col5      col6
0  0.215622  0.637428       NaN       NaN       NaN  0.241125
1       NaN       NaN       NaN       NaN  0.419948  0.553259
2       NaN       NaN  0.154342  0.719951       NaN       NaN
3       NaN  0.969642  0.924289  0.213746       NaN       NaN
4  0.971079       NaN       NaN       NaN  0.320278       NaN
5  0.461919  0.448829  0.380253  0.722185  0.019304  0.538564
6  0.361488  0.635634  0.445780  0.920459  0.218627  0.305238
7  0.645114  0.172539  0.036665  0.119121  0.528304  0.714588
8  0.347043  0.218876  0.142018  0.368253  0.136960  0.044611
9  0.418439  0.334608  0.792867  0.396132  0.611818  0.741815


In [31]:
individual = np.random.rand(6,3)
#print(individual)
for y in range(individual.shape[1]):
    #print(y)
    nan_indi = np.random.choice(3,2, replace=False)
    individual[nan_indi, y] = np.nan
    data_frame = pd.DataFrame(individual)
print(data_frame)


          0         1         2
0  0.373940  0.402847       NaN
1       NaN       NaN  0.740422
2       NaN       NaN       NaN
3  0.710578  0.689185  0.850300
4  0.999189  0.803609  0.559837
5  0.991874  0.128098  0.891445


In [32]:
data_frame.columns=['col1','col2','col3']
print(data_frame)

       col1      col2      col3
0  0.373940  0.402847       NaN
1       NaN       NaN  0.740422
2       NaN       NaN       NaN
3  0.710578  0.689185  0.850300
4  0.999189  0.803609  0.559837
5  0.991874  0.128098  0.891445


In [63]:
data_frame1 = data_frame.copy()
data_frame2 = data_frame.copy()
data_frame3 = data_frame.copy()
data_frame4 = data_frame.copy()
data_frame5 = data_frame.copy()
data_frame6 = data_frame.copy()
data_frame7 = data_frame.copy()
data_frame8 = data_frame.copy()

In [34]:
new_data1 = data_frame.dropna()
print(new_data1)

       col1      col2      col3
3  0.710578  0.689185  0.850300
4  0.999189  0.803609  0.559837
5  0.991874  0.128098  0.891445


In [35]:
data_frame.drop('col1', axis=1, inplace=True)
print(data_frame)

       col2      col3
0  0.402847       NaN
1       NaN  0.740422
2       NaN       NaN
3  0.689185  0.850300
4  0.803609  0.559837
5  0.128098  0.891445


In [36]:
data_frame1.drop(['col1','col2'], axis=1, inplace=True)
print(data_frame1)

       col3
0       NaN
1  0.740422
2       NaN
3  0.850300
4  0.559837
5  0.891445


In [37]:
data_frame2.fillna(6, inplace=True)
print(data_frame2)

       col1      col2      col3
0  0.373940  0.402847  6.000000
1  6.000000  6.000000  0.740422
2  6.000000  6.000000  6.000000
3  0.710578  0.689185  0.850300
4  0.999189  0.803609  0.559837
5  0.991874  0.128098  0.891445


In [38]:
data_frame3['col1'] = data_frame3['col2'].fillna(3)
print(data_frame3)

       col1      col2      col3
0  0.402847  0.402847       NaN
1  3.000000       NaN  0.740422
2  3.000000       NaN       NaN
3  0.689185  0.689185  0.850300
4  0.803609  0.803609  0.559837
5  0.128098  0.128098  0.891445


In [39]:
data_frame3['col2'] = data_frame3['col2'].fillna(data_frame3['col2'].mean())
print(data_frame3)

       col1      col2      col3
0  0.402847  0.402847       NaN
1  3.000000  0.505935  0.740422
2  3.000000  0.505935       NaN
3  0.689185  0.689185  0.850300
4  0.803609  0.803609  0.559837
5  0.128098  0.128098  0.891445


In [40]:
data_frame3['col3'] = data_frame3['col3'].fillna(data_frame3['col3'].max())
print(data_frame3)

       col1      col2      col3
0  0.402847  0.402847  0.891445
1  3.000000  0.505935  0.740422
2  3.000000  0.505935  0.891445
3  0.689185  0.689185  0.850300
4  0.803609  0.803609  0.559837
5  0.128098  0.128098  0.891445


In [41]:
import pandas as pd
import numpy as np
Dataset1_new = Dataset1.copy()
nan_add = Dataset1_new[61:71].copy()
#print(nan_add)
for z in range(nan_add.shape[1]):
    nan_add_rand = np.random.choice(nan_add.shape[0],4, replace=False)
    nan_add.iloc[nan_add_rand, z] = np.nan
Dataset1_new.iloc[61:71] = nan_add
print(Dataset1_new.iloc[61:71])

     Age     Sex   Bmi  Children Smoker     Region      Charges
61  25.0    male  33.0       4.0    NaN        NaN   4504.66240
62   NaN    male  24.0       NaN    NaN  northwest          NaN
63   NaN     NaN   NaN       1.0     no  northwest   4133.64165
64  20.0  female  22.0       0.0    yes  northwest          NaN
65  19.0     NaN  28.0       NaN    NaN        NaN          NaN
66  61.0  female   NaN       2.0     no        NaN  14235.07200
67   NaN     NaN   NaN       1.0     no  northwest   6389.37785
68   NaN  female  36.0       NaN     no  southeast          NaN
69  28.0    male  23.0       3.0    NaN        NaN  17663.14420
70  27.0     NaN   NaN       NaN    yes  southeast  16577.77950


In [137]:
import pandas as pd
import numpy as np
Dataset_frame_copy = Dataset_frame1.copy()
new_Dataset_frame_copy = Dataset_frame_copy[501:511].copy()
for a in range(new_Dataset_frame_copy.shape[1]):
    Dataset_frame_copy_nan = np.random.choice(new_Dataset_frame_copy.shape[1],3, replace=True)
    new_Dataset_frame_copy.iloc[Dataset_frame_copy_nan, a] = np.nan
Dataset_frame_copy.iloc[501:511] = new_Dataset_frame_copy
print(Dataset_frame_copy.iloc[501:511])

      age     sex    bmi  children smoker     region      charges
501   NaN    male    NaN       0.0    NaN        NaN   6837.36870
502   NaN    male  23.21       1.0    yes  southeast  22218.11490
503  19.0    male    NaN       0.0    yes  southeast          NaN
504   NaN     NaN  28.93       1.0     no  southeast          NaN
505  37.0     NaN    NaN       NaN    NaN        NaN   6796.86325
506  22.0    male  31.35       NaN     no  northwest   2643.26850
507  21.0     NaN  23.75       2.0    NaN  northwest   3077.09550
508  24.0  female  25.27       0.0     no  northeast   3044.21330
509  57.0  female  28.70       0.0     no  southwest  11455.28000
510  56.0    male  32.11       1.0     no  northeast  11763.00090


In [138]:
print(Dataset_frame2)

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]
