In [1]:
#info,index,column,rename,axis,astype,concate,condition,ignor_index,random row-column, shape[]
#replace with nun-non-null value, head(), tail(), fillna(), dropna(), drop, inplace(), max
#min,mean, quantile, median


In [2]:
import pandas as pd
a = [3,5,7]
df = pd.Series(a)
df

0    3
1    5
2    7
dtype: int64

In [3]:
df.info()

<class 'pandas.core.series.Series'>
RangeIndex: 3 entries, 0 to 2
Series name: None
Non-Null Count  Dtype
--------------  -----
3 non-null      int64
dtypes: int64(1)
memory usage: 156.0 bytes


In [4]:
a = (3,5,7)
df = pd.Series(a)
df

0    3
1    5
2    7
dtype: int64

In [5]:
dic = {
    'Name':['Maruf', 'Jidni'],
    'Roll': [884598, 884588]
    }
df = pd.Series(dic)
df

Name      [Maruf, Jidni]
Roll    [884598, 884588]
dtype: object

In [6]:
df.info()

<class 'pandas.core.series.Series'>
Index: 2 entries, Name to Roll
Series name: None
Non-Null Count  Dtype 
--------------  ----- 
2 non-null      object
dtypes: object(1)
memory usage: 140.0+ bytes


In [7]:
dic = {
    'Name' : ['Maruf', 'Rajin', 'Jidni'],
    'Roll' : [23, 56, 21],
    'dep' : ['cst', 'auto', 'cst']
}
df = pd.Series(dic, index=['Name', 'Roll', 'dep'])
df

Name    [Maruf, Rajin, Jidni]
Roll             [23, 56, 21]
dep          [cst, auto, cst]
dtype: object

In [8]:
df.info()

<class 'pandas.core.series.Series'>
Index: 3 entries, Name to dep
Series name: None
Non-Null Count  Dtype 
--------------  ----- 
3 non-null      object
dtypes: object(1)
memory usage: 156.0+ bytes


In [9]:
a = [[3,5,7]]
df = pd.DataFrame(a)
df


0  1  2
0  3  5  7

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       1 non-null      int64
 1   1       1 non-null      int64
 2   2       1 non-null      int64
dtypes: int64(3)
memory usage: 156.0 bytes


In [11]:
b = [3,5,7]
df2 = pd.DataFrame(b)
df2

0
0  3
1  5
2  7

In [12]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       3 non-null      int64
dtypes: int64(1)
memory usage: 156.0 bytes


In [13]:
a = [[3,5,7]]
df = pd.DataFrame(a, columns=['N1', 'N2', 'N3'])
df

N1  N2  N3
0   3   5   7

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   N1      1 non-null      int64
 1   N2      1 non-null      int64
 2   N3      1 non-null      int64
dtypes: int64(3)
memory usage: 156.0 bytes


In [15]:
b = [3,5,7]
df2 = pd.DataFrame(b, columns=['Rolls'])
df2

Rolls
0      3
1      5
2      7

In [16]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Rolls   3 non-null      int64
dtypes: int64(1)
memory usage: 156.0 bytes


In [17]:
b = [['maruf', 'jidni', 'rajin'],[3,5,7]]
df2 = pd.DataFrame(b)
df2

0      1      2
0  maruf  jidni  rajin
1      3      5      7

In [18]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       2 non-null      object
 1   1       2 non-null      object
 2   2       2 non-null      object
dtypes: object(3)
memory usage: 180.0+ bytes


In [19]:
b = [['maruf', 'jidni', 'rajin'],[3,5,7]]
df2 = pd.DataFrame(b, columns= ['col1', 'col2', 'col3'])
df2

col1   col2   col3
0  maruf  jidni  rajin
1      3      5      7

In [20]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   col1    2 non-null      object
 1   col2    2 non-null      object
 2   col3    2 non-null      object
dtypes: object(3)
memory usage: 180.0+ bytes


In [21]:
dic = {
    'Name' : ['Maruf', 'Rajin', 'Jidni', 'robin'],
    'Roll' : [23, 56, 21, 56],
    'dep' : ['cst', 'auto', 'cst', 'Et']
}
df = pd.DataFrame(dic)
df

Name  Roll   dep
0  Maruf    23   cst
1  Rajin    56  auto
2  Jidni    21   cst
3  robin    56    Et

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Roll    4 non-null      int64 
 2   dep     4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes


In [23]:
dic = {
    'Name' : ['Maruf', 'Rajin', 'Jidni', 'robin'],
    'Roll' : [23, 56, 21, 56],
    'dep' : ['cst', 'auto', 'cst', 'Et']
}
df = pd.DataFrame(dic)
#df = pd.DataFrame(dic, columns=['NAME','ROLL', 'DEP']) don't change like this
df

Name  Roll   dep
0  Maruf    23   cst
1  Rajin    56  auto
2  Jidni    21   cst
3  robin    56    Et

In [24]:
df = df.rename({'Name':'নাম', 'Roll':'রোল', 'dep':'ডিপারট্মেন্ট'}, axis=1)
df

নাম  রোল ডিপারট্মেন্ট
0  Maruf   23          cst
1  Rajin   56         auto
2  Jidni   21          cst
3  robin   56           Et

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   নাম           4 non-null      object
 1   রোল           4 non-null      int64 
 2   ডিপারট্মেন্ট  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes


In [26]:
dic = {
    'Name' : ['Maruf', 'Rajin', 'Jidni', 'robin'],
    'Roll' : [23, 56, 21, 56],
    'dep' : ['cst', 'auto', 'cst', 'Et']
}
df = pd.DataFrame(dic)
df

Name  Roll   dep
0  Maruf    23   cst
1  Rajin    56  auto
2  Jidni    21   cst
3  robin    56    Et

In [27]:
df['Roll']

0    23
1    56
2    21
3    56
Name: Roll, dtype: int64

In [28]:
df[['Roll']]

Roll
0    23
1    56
2    21
3    56

In [29]:
df[['Name']]

Name
0  Maruf
1  Rajin
2  Jidni
3  robin

In [30]:
df[['dep']]

dep
0   cst
1  auto
2   cst
3    Et

In [31]:
dic = {
    'Name' : ['Maruf', 'Rajin', 'Jidni', 'robin'],
    'Roll' : [2354367467, 564567756, 214567567, 56567457],
    'dep' : ['cst', 'auto', 'cst', 'Et']
}
df = pd.DataFrame(dic)
df

Name        Roll   dep
0  Maruf  2354367467   cst
1  Rajin   564567756  auto
2  Jidni   214567567   cst
3  robin    56567457    Et

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Roll    4 non-null      int64 
 2   dep     4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes


In [33]:
df[['Roll']].astype('int64')

Roll
0  2354367467
1   564567756
2   214567567
3    56567457

In [34]:
df[['Roll']].astype('int32')

Roll
0 -1940599829
1   564567756
2   214567567
3    56567457

In [35]:
df[['Roll']].astype('int16')

Roll
0 -13333
1 -24884
2   2703
3   9889

In [36]:
dic = {
    'Name' : ['Maruf', 'Rajin', 'Jidni', 'robin'],
    'Roll' : [230, 560, 210, 500],
    'dep' : ['cst', 'auto', 'cst', 'Et']
}
df = pd.DataFrame(dic)
df

Name  Roll   dep
0  Maruf   230   cst
1  Rajin   560  auto
2  Jidni   210   cst
3  robin   500    Et

In [37]:
df['Roll']>300 # can't use 2 dimesional array

0    False
1     True
2    False
3     True
Name: Roll, dtype: bool

In [38]:
df[df['Roll']>300]

Name  Roll   dep
1  Rajin   560  auto
3  robin   500    Et

In [39]:
df[df['Roll']>300]['Name']

1    Rajin
3    robin
Name: Name, dtype: object

In [40]:
dic1 = {
    'Name' : ['Maruf', 'Rajin', 'Jidni', 'robin'],
    'Roll' : [230, 560, 210, 500],
    'Dep' : ['cst', 'auto', 'cst', 'Et']
}
df3 = pd.DataFrame(dic)
df3

Name  Roll   dep
0  Maruf   230   cst
1  Rajin   560  auto
2  Jidni   210   cst
3  robin   500    Et

In [41]:
dic2 = {
    'name':['nibir','alimoon','sameer','aryan'],
    'roll':[435,65,5,67],
    'dep':['mec','sc','auto','cst']

}
df4 = pd.DataFrame(dic2)
print(df4)

      name  roll   dep
0    nibir   435   mec
1  alimoon    65    sc
2   sameer     5  auto
3    aryan    67   cst


In [42]:
new_dic = pd.concat([df3,df4])
print(new_dic)

    Name   Roll   dep     name   roll
0  Maruf  230.0   cst      NaN    NaN
1  Rajin  560.0  auto      NaN    NaN
2  Jidni  210.0   cst      NaN    NaN
3  robin  500.0    Et      NaN    NaN
0    NaN    NaN   mec    nibir  435.0
1    NaN    NaN    sc  alimoon   65.0
2    NaN    NaN  auto   sameer    5.0
3    NaN    NaN   cst    aryan   67.0


In [43]:
new_dic = pd.concat([df3,df4], axis=1)
print(new_dic)

    Name  Roll   dep     name  roll   dep
0  Maruf   230   cst    nibir   435   mec
1  Rajin   560  auto  alimoon    65    sc
2  Jidni   210   cst   sameer     5  auto
3  robin   500    Et    aryan    67   cst


In [44]:
dic1 = {
    'Name' : ['Maruf', 'Rajin', 'Jidni', 'robin'],
    'Roll' : [230, 560, 210, 500],
    'Dep' : ['cst', 'auto', 'cst', 'Et']
}
df3 = pd.DataFrame(dic1)
df3

Name  Roll   Dep
0  Maruf   230   cst
1  Rajin   560  auto
2  Jidni   210   cst
3  robin   500    Et

In [45]:
dic2 = {
    'Name':['nibir','alimoon','sameer','aryan'],
    'Roll':[435,65,5,67],
    'Dep':['mec','sc','auto','cst']

}
df4 = pd.DataFrame(dic2)
print(df4)

      Name  Roll   Dep
0    nibir   435   mec
1  alimoon    65    sc
2   sameer     5  auto
3    aryan    67   cst


In [46]:
new_dic2 = pd.concat([df3,df4])
print(new_dic2)

      Name  Roll   Dep
0    Maruf   230   cst
1    Rajin   560  auto
2    Jidni   210   cst
3    robin   500    Et
0    nibir   435   mec
1  alimoon    65    sc
2   sameer     5  auto
3    aryan    67   cst


In [47]:
new_dic2 = pd.concat([df3,df4], ignore_index=True)
print(new_dic2)

      Name  Roll   Dep
0    Maruf   230   cst
1    Rajin   560  auto
2    Jidni   210   cst
3    robin   500    Et
4    nibir   435   mec
5  alimoon    65    sc
6   sameer     5  auto
7    aryan    67   cst


In [48]:
import numpy as np
data = np.random.rand(10,5)
print(data)

[[0.90814151 0.65435327 0.34308738 0.12893987 0.83399323]
 [0.6501119  0.17897616 0.96662107 0.19443191 0.23243536]
 [0.14911029 0.90831639 0.14374052 0.09290841 0.12626842]
 [0.3214411  0.50739789 0.77279447 0.82147211 0.35373399]
 [0.31356468 0.4690129  0.6034165  0.87084721 0.14110072]
 [0.10801508 0.16714145 0.51770237 0.74615362 0.91333477]
 [0.37095153 0.78813179 0.73800663 0.83246727 0.83780032]
 [0.76405216 0.48962928 0.8854224  0.70410717 0.82965144]
 [0.80048434 0.12974349 0.29465444 0.76066796 0.58556156]
 [0.92946587 0.46024037 0.41875568 0.36220084 0.90719216]]


In [49]:
data = np.random.rand(10,5)
for x in data:
    print(x)

[0.38978336 0.74582345 0.78996256 0.00572895 0.19746908]
[0.84073654 0.71365906 0.91209206 0.60494344 0.19790457]
[0.89818037 0.55737366 0.69556134 0.64964229 0.98753201]
[0.27726471 0.75120934 0.16064132 0.11998476 0.71012402]
[0.39085733 0.10117148 0.1881413  0.23223321 0.94257646]
[0.71856129 0.47878334 0.18738386 0.56385951 0.07775634]
[0.05214276 0.86903975 0.05608169 0.64291192 0.77921286]
[0.79958252 0.1594089  0.16334648 0.57859971 0.28311146]
[0.98491167 0.10226095 0.77039069 0.83970849 0.60447472]
[0.79689132 0.67089279 0.27229187 0.41832386 0.69692301]


In [50]:
import numpy as np
data = np.random.rand(10,5)
for x in range(data.shape[1]):
    print(x)

0
1
2
3
4


In [51]:
import numpy as np
import pandas as pd
data = np.random.rand(10,5)
for x in range(data.shape[1]):
    nan_value = np.random.choice(6,4, replace=False)
    data[nan_value, x] = np.nan
    daf = pd.DataFrame(data)
print(daf)

          0         1         2         3         4
0       NaN       NaN       NaN  0.275144       NaN
1  0.944859       NaN       NaN       NaN  0.701736
2       NaN       NaN       NaN       NaN  0.836120
3  0.861215       NaN       NaN       NaN       NaN
4       NaN  0.704567  0.702749  0.677940       NaN
5       NaN  0.978491  0.663723       NaN       NaN
6  0.321116  0.420382  0.695145  0.838676  0.880812
7  0.336543  0.021901  0.635292  0.910458  0.001032
8  0.843806  0.478395  0.012475  0.427494  0.191364
9  0.206640  0.311170  0.601955  0.947819  0.350630


In [52]:
print(daf.head())

          0         1         2         3         4
0       NaN       NaN       NaN  0.275144       NaN
1  0.944859       NaN       NaN       NaN  0.701736
2       NaN       NaN       NaN       NaN  0.836120
3  0.861215       NaN       NaN       NaN       NaN
4       NaN  0.704567  0.702749  0.677940       NaN


In [53]:
print(daf.head(3))

          0   1   2         3         4
0       NaN NaN NaN  0.275144       NaN
1  0.944859 NaN NaN       NaN  0.701736
2       NaN NaN NaN       NaN  0.836120


In [54]:
import numpy as np
import pandas as pd
data = np.random.rand(10,5)
for x in range(data.shape[1]):
    nan_value = np.random.choice(6,3, replace=False)
    data[nan_value, x] = np.nan
    daf = pd.DataFrame(data)
print(daf)

          0         1         2         3         4
0       NaN       NaN       NaN  0.595876       NaN
1       NaN       NaN       NaN       NaN       NaN
2  0.503036  0.503915  0.267651  0.086445       NaN
3       NaN       NaN       NaN       NaN  0.541332
4  0.369974  0.798967  0.931031       NaN  0.679928
5  0.563684  0.885809  0.764259  0.086764  0.354929
6  0.303181  0.720812  0.109099  0.989769  0.886699
7  0.892532  0.669940  0.933147  0.545052  0.266787
8  0.455541  0.640160  0.427467  0.164526  0.522190
9  0.132653  0.944569  0.152079  0.994658  0.937363


In [55]:
daf.columns=['col1','col2','col3','col4', 'col5']
print(daf)

       col1      col2      col3      col4      col5
0       NaN       NaN       NaN  0.595876       NaN
1       NaN       NaN       NaN       NaN       NaN
2  0.503036  0.503915  0.267651  0.086445       NaN
3       NaN       NaN       NaN       NaN  0.541332
4  0.369974  0.798967  0.931031       NaN  0.679928
5  0.563684  0.885809  0.764259  0.086764  0.354929
6  0.303181  0.720812  0.109099  0.989769  0.886699
7  0.892532  0.669940  0.933147  0.545052  0.266787
8  0.455541  0.640160  0.427467  0.164526  0.522190
9  0.132653  0.944569  0.152079  0.994658  0.937363


In [56]:
daf1 = daf.copy()
daf2 = daf.copy()
daf3 = daf.copy()
daf4 = daf.copy()
daf5 = daf.copy()

In [57]:
daf.dropna()

col1      col2      col3      col4      col5
5  0.563684  0.885809  0.764259  0.086764  0.354929
6  0.303181  0.720812  0.109099  0.989769  0.886699
7  0.892532  0.669940  0.933147  0.545052  0.266787
8  0.455541  0.640160  0.427467  0.164526  0.522190
9  0.132653  0.944569  0.152079  0.994658  0.937363

In [58]:
daf = daf.dropna()
daf

col1      col2      col3      col4      col5
5  0.563684  0.885809  0.764259  0.086764  0.354929
6  0.303181  0.720812  0.109099  0.989769  0.886699
7  0.892532  0.669940  0.933147  0.545052  0.266787
8  0.455541  0.640160  0.427467  0.164526  0.522190
9  0.132653  0.944569  0.152079  0.994658  0.937363

In [59]:
daf1 = daf1.drop(['col3'], axis=1)

In [60]:
daf2.drop(['col5'], axis=1, inplace=True)

In [61]:
daf2

col1      col2      col3      col4
0       NaN       NaN       NaN  0.595876
1       NaN       NaN       NaN       NaN
2  0.503036  0.503915  0.267651  0.086445
3       NaN       NaN       NaN       NaN
4  0.369974  0.798967  0.931031       NaN
5  0.563684  0.885809  0.764259  0.086764
6  0.303181  0.720812  0.109099  0.989769
7  0.892532  0.669940  0.933147  0.545052
8  0.455541  0.640160  0.427467  0.164526
9  0.132653  0.944569  0.152079  0.994658

In [62]:
daf2 = daf2.drop(['col1','col2'], axis=1)
daf2

col3      col4
0       NaN  0.595876
1       NaN       NaN
2  0.267651  0.086445
3       NaN       NaN
4  0.931031       NaN
5  0.764259  0.086764
6  0.109099  0.989769
7  0.933147  0.545052
8  0.427467  0.164526
9  0.152079  0.994658

In [63]:
print(daf3)

       col1      col2      col3      col4      col5
0       NaN       NaN       NaN  0.595876       NaN
1       NaN       NaN       NaN       NaN       NaN
2  0.503036  0.503915  0.267651  0.086445       NaN
3       NaN       NaN       NaN       NaN  0.541332
4  0.369974  0.798967  0.931031       NaN  0.679928
5  0.563684  0.885809  0.764259  0.086764  0.354929
6  0.303181  0.720812  0.109099  0.989769  0.886699
7  0.892532  0.669940  0.933147  0.545052  0.266787
8  0.455541  0.640160  0.427467  0.164526  0.522190
9  0.132653  0.944569  0.152079  0.994658  0.937363


In [64]:
daf3.fillna(4, inplace=True)
daf3

col1      col2      col3      col4      col5
0  4.000000  4.000000  4.000000  0.595876  4.000000
1  4.000000  4.000000  4.000000  4.000000  4.000000
2  0.503036  0.503915  0.267651  0.086445  4.000000
3  4.000000  4.000000  4.000000  4.000000  0.541332
4  0.369974  0.798967  0.931031  4.000000  0.679928
5  0.563684  0.885809  0.764259  0.086764  0.354929
6  0.303181  0.720812  0.109099  0.989769  0.886699
7  0.892532  0.669940  0.933147  0.545052  0.266787
8  0.455541  0.640160  0.427467  0.164526  0.522190
9  0.132653  0.944569  0.152079  0.994658  0.937363

In [65]:
daf4

col1      col2      col3      col4      col5
0       NaN       NaN       NaN  0.595876       NaN
1       NaN       NaN       NaN       NaN       NaN
2  0.503036  0.503915  0.267651  0.086445       NaN
3       NaN       NaN       NaN       NaN  0.541332
4  0.369974  0.798967  0.931031       NaN  0.679928
5  0.563684  0.885809  0.764259  0.086764  0.354929
6  0.303181  0.720812  0.109099  0.989769  0.886699
7  0.892532  0.669940  0.933147  0.545052  0.266787
8  0.455541  0.640160  0.427467  0.164526  0.522190
9  0.132653  0.944569  0.152079  0.994658  0.937363

In [66]:
daf4.describe()

col1      col2      col3      col4      col5
count  7.000000  7.000000  7.000000  7.000000  7.000000
mean   0.460086  0.737739  0.512105  0.494727  0.598461
std    0.237893  0.151400  0.359470  0.397895  0.252642
min    0.132653  0.503915  0.109099  0.086445  0.266787
25%    0.336577  0.655050  0.209865  0.125645  0.438559
50%    0.455541  0.720812  0.427467  0.545052  0.541332
75%    0.533360  0.842388  0.847645  0.792823  0.783314
max    0.892532  0.944569  0.933147  0.994658  0.937363

In [67]:
daf4['col1'].mean()

np.float64(0.46008600189931004)

In [68]:
daf4['col2'].median()

np.float64(0.7208120530636624)

In [69]:
daf4['col2'].max()

np.float64(0.944569313861058)

In [70]:
daf4['col2'].min()

np.float64(0.5039147797686444)

In [71]:
daf4['col2'].quantile(.25)

np.float64(0.655049880709871)

In [72]:
daf4['col2'].quantile(.50)

np.float64(0.7208120530636624)

In [73]:
daf5

col1      col2      col3      col4      col5
0       NaN       NaN       NaN  0.595876       NaN
1       NaN       NaN       NaN       NaN       NaN
2  0.503036  0.503915  0.267651  0.086445       NaN
3       NaN       NaN       NaN       NaN  0.541332
4  0.369974  0.798967  0.931031       NaN  0.679928
5  0.563684  0.885809  0.764259  0.086764  0.354929
6  0.303181  0.720812  0.109099  0.989769  0.886699
7  0.892532  0.669940  0.933147  0.545052  0.266787
8  0.455541  0.640160  0.427467  0.164526  0.522190
9  0.132653  0.944569  0.152079  0.994658  0.937363

In [74]:
daf5['col1'].mean()

np.float64(0.46008600189931004)

In [75]:
daf5['col1'] = daf5['col1'].fillna(daf5['col1'].mean())

In [76]:
daf5

col1      col2      col3      col4      col5
0  0.460086       NaN       NaN  0.595876       NaN
1  0.460086       NaN       NaN       NaN       NaN
2  0.503036  0.503915  0.267651  0.086445       NaN
3  0.460086       NaN       NaN       NaN  0.541332
4  0.369974  0.798967  0.931031       NaN  0.679928
5  0.563684  0.885809  0.764259  0.086764  0.354929
6  0.303181  0.720812  0.109099  0.989769  0.886699
7  0.892532  0.669940  0.933147  0.545052  0.266787
8  0.455541  0.640160  0.427467  0.164526  0.522190
9  0.132653  0.944569  0.152079  0.994658  0.937363

In [77]:
daf5 = daf5.fillna({
    'col2': 4,
    'col3': 6,
    'col4': 3,
    'col5': 2
})

In [78]:
daf5

col1      col2      col3      col4      col5
0  0.460086  4.000000  6.000000  0.595876  2.000000
1  0.460086  4.000000  6.000000  3.000000  2.000000
2  0.503036  0.503915  0.267651  0.086445  2.000000
3  0.460086  4.000000  6.000000  3.000000  0.541332
4  0.369974  0.798967  0.931031  3.000000  0.679928
5  0.563684  0.885809  0.764259  0.086764  0.354929
6  0.303181  0.720812  0.109099  0.989769  0.886699
7  0.892532  0.669940  0.933147  0.545052  0.266787
8  0.455541  0.640160  0.427467  0.164526  0.522190
9  0.132653  0.944569  0.152079  0.994658  0.937363