In [1]:
#info,index,column,rename,axis,astype,concate,condition,ignor_index,random row-column, shape[]
#replace with nun-non-null value, head(), tail(), fillna(), dropna(), drop, inplace(), max
#min,mean, quantile, median

In [2]:
import pandas as pd
import numpy as np
Dataset1 = pd.read_csv('insurance (1).csv')
print(Dataset1)


      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [3]:
Dataset_frame1 = Dataset1.copy()
Dataset_frame2 = Dataset1.copy()
Dataset_frame3 = Dataset1.copy()
Dataset_frame4 = Dataset1.copy()
Dataset_frame5 = Dataset1.copy()
Dataset_frame6 = Dataset1.copy()

In [4]:
print(Dataset1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB
None


In [5]:
print(Dataset1.dtypes)

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object


In [6]:
alldata = pd.DataFrame(Dataset1, index=[60,70,80,90])
print(alldata)

    age     sex     bmi  children smoker     region      charges
60   43    male  27.360         3     no  northeast   8606.21740
70   27  female  24.750         0    yes  southeast  16577.77950
80   31    male  26.885         1     no  northeast   4441.21315
90   21  female  39.490         0     no  southeast   2026.97410


In [7]:
#alldata = pd.DataFrame(Dataset1, index=[41:51])
#print(alldata)                                         don't do this

In [8]:
print(Dataset1.head())

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520


In [9]:
print(Dataset1.head(3))

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620


In [10]:
print(Dataset1.tail())

      age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603


In [11]:
print(Dataset1.tail(4))

      age     sex    bmi  children smoker     region     charges
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603


In [12]:
print(Dataset1[101:201])

     age     sex     bmi  children smoker     region      charges
101   30    male  25.460         0     no  northeast   3645.08940
102   18  female  30.115         0     no  northeast  21344.84670
103   61  female  29.920         3    yes  southeast  30942.19180
104   34  female  27.500         1     no  southwest   5003.85300
105   20    male  28.025         1    yes  northwest  17560.37975
..   ...     ...     ...       ...    ...        ...          ...
196   39  female  32.800         0     no  southwest   5649.71500
197   45  female  28.600         2     no  southeast   8516.82900
198   51  female  18.050         0     no  northwest   9644.25250
199   64  female  39.330         0     no  northeast  14901.51670
200   19  female  32.110         0     no  northwest   2130.67590

[100 rows x 7 columns]


In [13]:
#column Rename
#Dataset1.rename(columns=['Age','Sex','Bmi','Children','Smoker','Region','Charges'], inplace=True) X Don't
Dataset1.rename({'age':'Age','sex':'Sex','bmi':'Bmi','children':'Children','smoker':'Smoker','region':'Region','charges':'Charges'}, axis=1, inplace=True)
print(Dataset1)

      Age     Sex     Bmi  Children Smoker     Region      Charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [14]:
#new_dataset = pd.DataFrame(Dataset1, columns=['AGE','SEX','BMI','CHILDREN','SMOKER','REGION','CHARGES'])
#print(new_dataset) x DON'T

In [15]:
Dataset1['Region'][61:71]

61    southeast
62    northwest
63    northwest
64    northwest
65    southwest
66    southwest
67    northwest
68    southeast
69    southeast
70    southeast
Name: Region, dtype: object

In [16]:
Dataset1['Age'] = Dataset1['Age'].astype(str, errors='ignore')
print(Dataset1)

     Age     Sex     Bmi  Children Smoker     Region      Charges
0     19  female  27.900         0    yes  southwest  16884.92400
1     18    male  33.770         1     no  southeast   1725.55230
2     28    male  33.000         3     no  southeast   4449.46200
3     33    male  22.705         0     no  northwest  21984.47061
4     32    male  28.880         0     no  northwest   3866.85520
...   ..     ...     ...       ...    ...        ...          ...
1333  50    male  30.970         3     no  northwest  10600.54830
1334  18  female  31.920         0     no  northeast   2205.98080
1335  18  female  36.850         0     no  southeast   1629.83350
1336  21  female  25.800         0     no  southwest   2007.94500
1337  61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [17]:
print(Dataset1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       1338 non-null   object 
 1   Sex       1338 non-null   object 
 2   Bmi       1338 non-null   float64
 3   Children  1338 non-null   int64  
 4   Smoker    1338 non-null   object 
 5   Region    1338 non-null   object 
 6   Charges   1338 non-null   float64
dtypes: float64(2), int64(1), object(4)
memory usage: 73.3+ KB
None


In [18]:
Dataset1['Age'] = Dataset1['Age'].astype(int, errors='ignore')
print(Dataset1)

      Age     Sex     Bmi  Children Smoker     Region      Charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [19]:
print(Dataset1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       1338 non-null   int64  
 1   Sex       1338 non-null   object 
 2   Bmi       1338 non-null   float64
 3   Children  1338 non-null   int64  
 4   Smoker    1338 non-null   object 
 5   Region    1338 non-null   object 
 6   Charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB
None


In [20]:
Dataset1['Bmi'] = Dataset1['Bmi'].astype(int, errors='ignore')
print(Dataset1)

      Age     Sex  Bmi  Children Smoker     Region      Charges
0      19  female   27         0    yes  southwest  16884.92400
1      18    male   33         1     no  southeast   1725.55230
2      28    male   33         3     no  southeast   4449.46200
3      33    male   22         0     no  northwest  21984.47061
4      32    male   28         0     no  northwest   3866.85520
...   ...     ...  ...       ...    ...        ...          ...
1333   50    male   30         3     no  northwest  10600.54830
1334   18  female   31         0     no  northeast   2205.98080
1335   18  female   36         0     no  southeast   1629.83350
1336   21  female   25         0     no  southwest   2007.94500
1337   61  female   29         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [21]:
Dataset1['Bmi'] = Dataset1['Bmi'].astype(float, errors='ignore')
print(Dataset1)

      Age     Sex   Bmi  Children Smoker     Region      Charges
0      19  female  27.0         0    yes  southwest  16884.92400
1      18    male  33.0         1     no  southeast   1725.55230
2      28    male  33.0         3     no  southeast   4449.46200
3      33    male  22.0         0     no  northwest  21984.47061
4      32    male  28.0         0     no  northwest   3866.85520
...   ...     ...   ...       ...    ...        ...          ...
1333   50    male  30.0         3     no  northwest  10600.54830
1334   18  female  31.0         0     no  northeast   2205.98080
1335   18  female  36.0         0     no  southeast   1629.83350
1336   21  female  25.0         0     no  southwest   2007.94500
1337   61  female  29.0         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [22]:
Dataset1['Sex'] = Dataset1['Sex'].astype('category')
print(Dataset1)

      Age     Sex   Bmi  Children Smoker     Region      Charges
0      19  female  27.0         0    yes  southwest  16884.92400
1      18    male  33.0         1     no  southeast   1725.55230
2      28    male  33.0         3     no  southeast   4449.46200
3      33    male  22.0         0     no  northwest  21984.47061
4      32    male  28.0         0     no  northwest   3866.85520
...   ...     ...   ...       ...    ...        ...          ...
1333   50    male  30.0         3     no  northwest  10600.54830
1334   18  female  31.0         0     no  northeast   2205.98080
1335   18  female  36.0         0     no  southeast   1629.83350
1336   21  female  25.0         0     no  southwest   2007.94500
1337   61  female  29.0         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [23]:
print(Dataset1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype   
---  ------    --------------  -----   
 0   Age       1338 non-null   int64   
 1   Sex       1338 non-null   category
 2   Bmi       1338 non-null   float64 
 3   Children  1338 non-null   int64   
 4   Smoker    1338 non-null   object  
 5   Region    1338 non-null   object  
 6   Charges   1338 non-null   float64 
dtypes: category(1), float64(2), int64(2), object(2)
memory usage: 64.3+ KB
None


In [24]:
Dataset1['Sex'] = Dataset1['Sex'].astype(str, errors='ignore')
print(Dataset1)

      Age     Sex   Bmi  Children Smoker     Region      Charges
0      19  female  27.0         0    yes  southwest  16884.92400
1      18    male  33.0         1     no  southeast   1725.55230
2      28    male  33.0         3     no  southeast   4449.46200
3      33    male  22.0         0     no  northwest  21984.47061
4      32    male  28.0         0     no  northwest   3866.85520
...   ...     ...   ...       ...    ...        ...          ...
1333   50    male  30.0         3     no  northwest  10600.54830
1334   18  female  31.0         0     no  northeast   2205.98080
1335   18  female  36.0         0     no  southeast   1629.83350
1336   21  female  25.0         0     no  southwest   2007.94500
1337   61  female  29.0         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [25]:
print(Dataset1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       1338 non-null   int64  
 1   Sex       1338 non-null   object 
 2   Bmi       1338 non-null   float64
 3   Children  1338 non-null   int64  
 4   Smoker    1338 non-null   object 
 5   Region    1338 non-null   object 
 6   Charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB
None


In [26]:
top = Dataset1.head()
bottom = Dataset1.tail()
random = Dataset1[601:606]
a_new_datset = pd.concat([top,bottom,random], ignore_index=True)
print(a_new_datset)

    Age     Sex   Bmi  Children Smoker     Region      Charges
0    19  female  27.0         0    yes  southwest  16884.92400
1    18    male  33.0         1     no  southeast   1725.55230
2    28    male  33.0         3     no  southeast   4449.46200
3    33    male  22.0         0     no  northwest  21984.47061
4    32    male  28.0         0     no  northwest   3866.85520
5    50    male  30.0         3     no  northwest  10600.54830
6    18  female  31.0         0     no  northeast   2205.98080
7    18  female  36.0         0     no  southeast   1629.83350
8    21  female  25.0         0     no  southwest   2007.94500
9    61  female  29.0         0    yes  northwest  29141.36030
10   51    male  31.0         0     no  northwest   9174.13565
11   56  female  25.0         0     no  southwest  11070.53500
12   64  female  39.0         3     no  southeast  16085.12750
13   19  female  28.0         0    yes  northwest  17468.98390
14   51  female  34.0         0     no  southeast   928

In [27]:
change_bottom = Dataset1.tail(2).rename(columns={
    'Age':'AGE',
    'Sex':'SEX',
    'Bmi':'BMI',
    'Children':'CHILDREN',
    'Smoker':'SMOKER',
    'Region':'REGION',
    'Charges':'CHARGES'
    })
change_bottom = change_bottom.reset_index(drop=True)
change_top = Dataset1.head(2)
change_top = change_top.reset_index(drop=True)
change_center = Dataset1[1001:1003].rename(columns={
    'Age':'AGE',
    'Sex':'SEX',
    'Bmi':'BMI',
    'Children':'CHILDREN',
    'Smoker':'SMOKER',
    'Region':'REGION',
})
change_center = change_center.reset_index(drop=True)
b_new_set = pd.concat([change_bottom, change_top, change_center], axis=1)
print(b_new_set)

   AGE     SEX   BMI  CHILDREN  SMOKER     REGION     CHARGES  Age     Sex  \
0   21  female  25.0         0      no  southwest   2007.9450   19  female   
1   61  female  29.0         0     yes  northwest  29141.3603   18    male   

    Bmi  ...  Smoker     Region     Charges  AGE   SEX   BMI  CHILDREN  \
0  27.0  ...     yes  southwest  16884.9240   24  male  32.0         0   
1  33.0  ...      no  southeast   1725.5523   24  male  25.0         0   

   SMOKER     REGION    Charges  
0     yes  southwest  34472.841  
1      no  southwest   1972.950  

[2 rows x 21 columns]


In [28]:
import numpy as np
randomly = np.random.rand(10,6)
for i in randomly:
    print(i)

[0.31096295 0.25505305 0.14375606 0.24112846 0.22136983 0.84271592]
[0.97056531 0.51507992 0.55394139 0.34804717 0.45484605 0.39813044]
[0.07882527 0.9890557  0.05918163 0.60792613 0.74359443 0.26206699]
[0.1346401  0.22216617 0.90864346 0.82724007 0.51402883 0.28587331]
[0.79534805 0.23613799 0.15740589 0.51105003 0.1492837  0.87728589]
[0.35506604 0.22395065 0.68497546 0.64163218 0.42682983 0.43883004]
[0.35650459 0.32546234 0.63169708 0.5732841  0.8618877  0.1812673 ]
[0.81626455 0.26105714 0.92347457 0.63116711 0.21276425 0.63714677]
[0.94402228 0.08149357 0.70861932 0.97372898 0.80837816 0.56936122]
[0.97719974 0.87168726 0.14623005 0.4861998  0.83973959 0.49399965]


In [29]:
import pandas as pd
import numpy as np
random_col = np.random.rand(10,6)
for i in range(random_col.shape[1]):
    nan_value = np.random.choice(5,3, replace=False)
    random_col[nan_value, i] = np.nan
    data_f = pd.DataFrame(random_col)
print(data_f)

          0         1         2         3         4         5
0  0.168526       NaN       NaN  0.524919       NaN       NaN
1       NaN       NaN  0.979200       NaN       NaN  0.844495
2       NaN  0.569936       NaN       NaN       NaN       NaN
3  0.728102       NaN  0.528194  0.301181  0.660164  0.210746
4       NaN  0.890040       NaN       NaN  0.224745       NaN
5  0.247654  0.779544  0.539785  0.301281  0.282748  0.862021
6  0.268858  0.891497  0.833522  0.368466  0.086901  0.753507
7  0.377755  0.019701  0.105759  0.314220  0.596212  0.942359
8  0.247097  0.162080  0.656527  0.068405  0.699499  0.346248
9  0.394651  0.712792  0.274866  0.605539  0.276638  0.766754


In [30]:
data_f.columns=['col1','col2','col3','col4','col5','col6']
print(data_f)

       col1      col2      col3      col4      col5      col6
0  0.168526       NaN       NaN  0.524919       NaN       NaN
1       NaN       NaN  0.979200       NaN       NaN  0.844495
2       NaN  0.569936       NaN       NaN       NaN       NaN
3  0.728102       NaN  0.528194  0.301181  0.660164  0.210746
4       NaN  0.890040       NaN       NaN  0.224745       NaN
5  0.247654  0.779544  0.539785  0.301281  0.282748  0.862021
6  0.268858  0.891497  0.833522  0.368466  0.086901  0.753507
7  0.377755  0.019701  0.105759  0.314220  0.596212  0.942359
8  0.247097  0.162080  0.656527  0.068405  0.699499  0.346248
9  0.394651  0.712792  0.274866  0.605539  0.276638  0.766754


In [31]:
individual = np.random.rand(6,3)
#print(individual)
for y in range(individual.shape[1]):
    #print(y)
    nan_indi = np.random.choice(3,2, replace=False)
    individual[nan_indi, y] = np.nan
    data_frame = pd.DataFrame(individual)
print(data_frame)


          0         1         2
0  0.753237  0.973593       NaN
1       NaN       NaN  0.705296
2       NaN       NaN       NaN
3  0.534288  0.531666  0.894421
4  0.382854  0.490834  0.245330
5  0.898398  0.958661  0.366813


In [32]:
data_frame.columns=['col1','col2','col3']
print(data_frame)

       col1      col2      col3
0  0.753237  0.973593       NaN
1       NaN       NaN  0.705296
2       NaN       NaN       NaN
3  0.534288  0.531666  0.894421
4  0.382854  0.490834  0.245330
5  0.898398  0.958661  0.366813


In [33]:
data_frame1 = data_frame.copy()
data_frame2 = data_frame.copy()
data_frame3 = data_frame.copy()
data_frame4 = data_frame.copy()
data_frame5 = data_frame.copy()
data_frame6 = data_frame.copy()
data_frame7 = data_frame.copy()
data_frame8 = data_frame.copy()

In [34]:
new_data1 = data_frame.dropna()
print(new_data1)

       col1      col2      col3
3  0.534288  0.531666  0.894421
4  0.382854  0.490834  0.245330
5  0.898398  0.958661  0.366813


In [35]:
data_frame.drop('col1', axis=1, inplace=True)
print(data_frame)

       col2      col3
0  0.973593       NaN
1       NaN  0.705296
2       NaN       NaN
3  0.531666  0.894421
4  0.490834  0.245330
5  0.958661  0.366813


In [36]:
data_frame1.drop(['col1','col2'], axis=1, inplace=True)
print(data_frame1)

       col3
0       NaN
1  0.705296
2       NaN
3  0.894421
4  0.245330
5  0.366813


In [37]:
data_frame2.fillna(6, inplace=True)
print(data_frame2)

       col1      col2      col3
0  0.753237  0.973593  6.000000
1  6.000000  6.000000  0.705296
2  6.000000  6.000000  6.000000
3  0.534288  0.531666  0.894421
4  0.382854  0.490834  0.245330
5  0.898398  0.958661  0.366813


In [38]:
data_frame3['col1'] = data_frame3['col2'].fillna(3)
print(data_frame3)

       col1      col2      col3
0  0.973593  0.973593       NaN
1  3.000000       NaN  0.705296
2  3.000000       NaN       NaN
3  0.531666  0.531666  0.894421
4  0.490834  0.490834  0.245330
5  0.958661  0.958661  0.366813


In [39]:
data_frame3['col2'] = data_frame3['col2'].fillna(data_frame3['col2'].mean())
print(data_frame3)

       col1      col2      col3
0  0.973593  0.973593       NaN
1  3.000000  0.738689  0.705296
2  3.000000  0.738689       NaN
3  0.531666  0.531666  0.894421
4  0.490834  0.490834  0.245330
5  0.958661  0.958661  0.366813


In [40]:
data_frame3['col3'] = data_frame3['col3'].fillna(data_frame3['col3'].max())
print(data_frame3)

       col1      col2      col3
0  0.973593  0.973593  0.894421
1  3.000000  0.738689  0.705296
2  3.000000  0.738689  0.894421
3  0.531666  0.531666  0.894421
4  0.490834  0.490834  0.245330
5  0.958661  0.958661  0.366813


In [41]:
import pandas as pd
import numpy as np
Dataset1_new = Dataset1.copy()
nan_add = Dataset1_new[61:71].copy()
#print(nan_add)
for z in range(nan_add.shape[1]):
    nan_add_rand = np.random.choice(nan_add.shape[0],4, replace=False)
    nan_add.iloc[nan_add_rand, z] = np.nan
Dataset1_new.iloc[61:71] = nan_add
print(Dataset1_new.iloc[61:71])

     Age     Sex   Bmi  Children Smoker     Region      Charges
61  25.0     NaN   NaN       NaN     no        NaN          NaN
62  64.0     NaN   NaN       NaN     no        NaN  30166.61817
63  28.0  female  25.0       NaN     no  northwest   4133.64165
64   NaN  female   NaN       NaN    NaN  northwest          NaN
65   NaN  female  28.0       0.0    NaN        NaN   1743.21400
66   NaN     NaN  39.0       2.0    NaN        NaN  14235.07200
67  40.0    male  26.0       1.0     no  northwest   6389.37785
68  40.0  female  36.0       0.0     no  southeast          NaN
69   NaN     NaN   NaN       3.0    yes  southeast  17663.14420
70  27.0  female  24.0       0.0    NaN  southeast          NaN


In [42]:
import pandas as pd
import numpy as np
Dataset_frame_copy = Dataset_frame1.copy()
new_Dataset_frame_copy = Dataset_frame_copy[501:511].copy()
for a in range(new_Dataset_frame_copy.shape[1]):
    Dataset_frame_copy_nan = np.random.choice(new_Dataset_frame_copy.shape[0],3, replace=True)
    new_Dataset_frame_copy.iloc[Dataset_frame_copy_nan, a] = np.nan
Dataset_frame_copy.iloc[501:511] = new_Dataset_frame_copy
print(Dataset_frame_copy.iloc[501:511])

      age     sex     bmi  children smoker     region      charges
501   NaN    male  26.030       0.0     no        NaN   6837.36870
502  51.0    male  23.210       1.0    yes  southeast  22218.11490
503  19.0    male  30.250       NaN    yes  southeast  32548.34050
504  38.0  female     NaN       1.0     no  southeast          NaN
505  37.0    male  30.875       3.0     no  northwest   6796.86325
506  22.0     NaN     NaN       NaN     no        NaN   2643.26850
507  21.0    male     NaN       2.0     no  northwest   3077.09550
508   NaN     NaN  25.270       0.0    NaN        NaN          NaN
509  57.0  female  28.700       NaN     no  southwest  11455.28000
510   NaN    male  32.110       1.0    NaN  northeast          NaN


In [43]:
import numpy as np
import pandas as pd
Dataset_frame2_copy = Dataset_frame2.copy()
copy_Dataset_frame_copy = Dataset_frame2_copy[751:761].copy()
for b in range(copy_Dataset_frame_copy.shape[1]):
    nan_copy_Dataset_frame_copy = np.random.choice(copy_Dataset_frame_copy.shape[0], 2, replace=True)
    copy_Dataset_frame_copy.iloc[nan_copy_Dataset_frame_copy, b] = np.nan
Dataset_frame2_copy.iloc[751:761] = copy_Dataset_frame_copy
print(Dataset_frame2_copy.iloc[751:761])

      age     sex     bmi  children smoker     region      charges
751   NaN    male     NaN       0.0     no  northwest   1906.35825
752  64.0     NaN  37.905       NaN     no  northwest          NaN
753  58.0  female  22.770       0.0     no  southeast  11833.78230
754  24.0    male  33.630       4.0     no  northeast  17128.42608
755  31.0    male     NaN       2.0     no        NaN   5031.26955
756   NaN  female  22.800       3.0    NaN  northeast   7985.81500
757  47.0     NaN  27.830       0.0    yes  southeast  23065.42070
758  30.0    male  37.430       3.0     no  northeast          NaN
759  18.0    male  38.170       0.0    yes  southeast  36307.79830
760  22.0  female  34.580       2.0    NaN  northeast   3925.75820


In [44]:
#Dataset_frame2_copy.iloc[751:761].dropna()

In [45]:
#Dataset_frame2_copy.iloc[751:761].drop('sex', axis=1)
#Dataset_frame2_copy.iloc[751:761].drop(['sex', 'children'], axis=1)

In [46]:
#Dataset_frame2_copy.iloc[751:761].fillna(24)

In [47]:
#Dataset_frame2_copy.iloc[751:761]['children'].mean()