In [232]:
#info,index,column,rename,axis,astype,concate,condition,ignor_index,random row-column, shape[]
#replace with nun-non-null value, head(), tail(), fillna(), dropna(), drop, inplace(), max
#min,mean, quantile, median

In [233]:
import pandas as pd
import numpy as np
Dataset1 = pd.read_csv('insurance (1).csv')
print(Dataset1)

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [234]:
print(Dataset1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB
None


In [235]:
print(Dataset1.dtypes)

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object


In [236]:
alldata = pd.DataFrame(Dataset1, index=[60,70,80,90])
print(alldata)

    age     sex     bmi  children smoker     region      charges
60   43    male  27.360         3     no  northeast   8606.21740
70   27  female  24.750         0    yes  southeast  16577.77950
80   31    male  26.885         1     no  northeast   4441.21315
90   21  female  39.490         0     no  southeast   2026.97410


In [237]:
#alldata = pd.DataFrame(Dataset1, index=[41:51])
#print(alldata)                                         don't do this

In [238]:
print(Dataset1.head())

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520


In [239]:
print(Dataset1.head(3))

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620


In [240]:
print(Dataset1.tail())

      age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603


In [241]:
print(Dataset1.tail(4))

      age     sex    bmi  children smoker     region     charges
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603


In [242]:
print(Dataset1[101:201])

     age     sex     bmi  children smoker     region      charges
101   30    male  25.460         0     no  northeast   3645.08940
102   18  female  30.115         0     no  northeast  21344.84670
103   61  female  29.920         3    yes  southeast  30942.19180
104   34  female  27.500         1     no  southwest   5003.85300
105   20    male  28.025         1    yes  northwest  17560.37975
..   ...     ...     ...       ...    ...        ...          ...
196   39  female  32.800         0     no  southwest   5649.71500
197   45  female  28.600         2     no  southeast   8516.82900
198   51  female  18.050         0     no  northwest   9644.25250
199   64  female  39.330         0     no  northeast  14901.51670
200   19  female  32.110         0     no  northwest   2130.67590

[100 rows x 7 columns]


In [243]:
#column Rename
#Dataset1.rename(columns=['Age','Sex','Bmi','Children','Smoker','Region','Charges'], inplace=True) X Don't
Dataset1.rename({'age':'Age','sex':'Sex','bmi':'Bmi','children':'Children','smoker':'Smoker','region':'Region','charges':'Charges'}, axis=1, inplace=True)
print(Dataset1)

      Age     Sex     Bmi  Children Smoker     Region      Charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [244]:
#new_dataset = pd.DataFrame(Dataset1, columns=['AGE','SEX','BMI','CHILDREN','SMOKER','REGION','CHARGES'])
#print(new_dataset) x DON'T

In [245]:
Dataset1['Region'][61:71]

61    southeast
62    northwest
63    northwest
64    northwest
65    southwest
66    southwest
67    northwest
68    southeast
69    southeast
70    southeast
Name: Region, dtype: object

In [246]:
Dataset1['Age'] = Dataset1['Age'].astype(str, errors='ignore')
print(Dataset1)

     Age     Sex     Bmi  Children Smoker     Region      Charges
0     19  female  27.900         0    yes  southwest  16884.92400
1     18    male  33.770         1     no  southeast   1725.55230
2     28    male  33.000         3     no  southeast   4449.46200
3     33    male  22.705         0     no  northwest  21984.47061
4     32    male  28.880         0     no  northwest   3866.85520
...   ..     ...     ...       ...    ...        ...          ...
1333  50    male  30.970         3     no  northwest  10600.54830
1334  18  female  31.920         0     no  northeast   2205.98080
1335  18  female  36.850         0     no  southeast   1629.83350
1336  21  female  25.800         0     no  southwest   2007.94500
1337  61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [247]:
print(Dataset1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       1338 non-null   object 
 1   Sex       1338 non-null   object 
 2   Bmi       1338 non-null   float64
 3   Children  1338 non-null   int64  
 4   Smoker    1338 non-null   object 
 5   Region    1338 non-null   object 
 6   Charges   1338 non-null   float64
dtypes: float64(2), int64(1), object(4)
memory usage: 73.3+ KB
None


In [248]:
Dataset1['Age'] = Dataset1['Age'].astype(int, errors='ignore')
print(Dataset1)

      Age     Sex     Bmi  Children Smoker     Region      Charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [249]:
print(Dataset1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       1338 non-null   int64  
 1   Sex       1338 non-null   object 
 2   Bmi       1338 non-null   float64
 3   Children  1338 non-null   int64  
 4   Smoker    1338 non-null   object 
 5   Region    1338 non-null   object 
 6   Charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB
None


In [250]:
Dataset1['Bmi'] = Dataset1['Bmi'].astype(int, errors='ignore')
print(Dataset1)

      Age     Sex  Bmi  Children Smoker     Region      Charges
0      19  female   27         0    yes  southwest  16884.92400
1      18    male   33         1     no  southeast   1725.55230
2      28    male   33         3     no  southeast   4449.46200
3      33    male   22         0     no  northwest  21984.47061
4      32    male   28         0     no  northwest   3866.85520
...   ...     ...  ...       ...    ...        ...          ...
1333   50    male   30         3     no  northwest  10600.54830
1334   18  female   31         0     no  northeast   2205.98080
1335   18  female   36         0     no  southeast   1629.83350
1336   21  female   25         0     no  southwest   2007.94500
1337   61  female   29         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [251]:
Dataset1['Bmi'] = Dataset1['Bmi'].astype(float, errors='ignore')
print(Dataset1)

      Age     Sex   Bmi  Children Smoker     Region      Charges
0      19  female  27.0         0    yes  southwest  16884.92400
1      18    male  33.0         1     no  southeast   1725.55230
2      28    male  33.0         3     no  southeast   4449.46200
3      33    male  22.0         0     no  northwest  21984.47061
4      32    male  28.0         0     no  northwest   3866.85520
...   ...     ...   ...       ...    ...        ...          ...
1333   50    male  30.0         3     no  northwest  10600.54830
1334   18  female  31.0         0     no  northeast   2205.98080
1335   18  female  36.0         0     no  southeast   1629.83350
1336   21  female  25.0         0     no  southwest   2007.94500
1337   61  female  29.0         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [252]:
Dataset1['Sex'] = Dataset1['Sex'].astype('category')
print(Dataset1)

      Age     Sex   Bmi  Children Smoker     Region      Charges
0      19  female  27.0         0    yes  southwest  16884.92400
1      18    male  33.0         1     no  southeast   1725.55230
2      28    male  33.0         3     no  southeast   4449.46200
3      33    male  22.0         0     no  northwest  21984.47061
4      32    male  28.0         0     no  northwest   3866.85520
...   ...     ...   ...       ...    ...        ...          ...
1333   50    male  30.0         3     no  northwest  10600.54830
1334   18  female  31.0         0     no  northeast   2205.98080
1335   18  female  36.0         0     no  southeast   1629.83350
1336   21  female  25.0         0     no  southwest   2007.94500
1337   61  female  29.0         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [253]:
print(Dataset1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype   
---  ------    --------------  -----   
 0   Age       1338 non-null   int64   
 1   Sex       1338 non-null   category
 2   Bmi       1338 non-null   float64 
 3   Children  1338 non-null   int64   
 4   Smoker    1338 non-null   object  
 5   Region    1338 non-null   object  
 6   Charges   1338 non-null   float64 
dtypes: category(1), float64(2), int64(2), object(2)
memory usage: 64.3+ KB
None


In [254]:
Dataset1['Sex'] = Dataset1['Sex'].astype(str, errors='ignore')
print(Dataset1)

      Age     Sex   Bmi  Children Smoker     Region      Charges
0      19  female  27.0         0    yes  southwest  16884.92400
1      18    male  33.0         1     no  southeast   1725.55230
2      28    male  33.0         3     no  southeast   4449.46200
3      33    male  22.0         0     no  northwest  21984.47061
4      32    male  28.0         0     no  northwest   3866.85520
...   ...     ...   ...       ...    ...        ...          ...
1333   50    male  30.0         3     no  northwest  10600.54830
1334   18  female  31.0         0     no  northeast   2205.98080
1335   18  female  36.0         0     no  southeast   1629.83350
1336   21  female  25.0         0     no  southwest   2007.94500
1337   61  female  29.0         0    yes  northwest  29141.36030

[1338 rows x 7 columns]


In [255]:
print(Dataset1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       1338 non-null   int64  
 1   Sex       1338 non-null   object 
 2   Bmi       1338 non-null   float64
 3   Children  1338 non-null   int64  
 4   Smoker    1338 non-null   object 
 5   Region    1338 non-null   object 
 6   Charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB
None


In [256]:
top = Dataset1.head()
bottom = Dataset1.tail()
random = Dataset1[601:606]
a_new_datset = pd.concat([top,bottom,random], ignore_index=True)
print(a_new_datset)

    Age     Sex   Bmi  Children Smoker     Region      Charges
0    19  female  27.0         0    yes  southwest  16884.92400
1    18    male  33.0         1     no  southeast   1725.55230
2    28    male  33.0         3     no  southeast   4449.46200
3    33    male  22.0         0     no  northwest  21984.47061
4    32    male  28.0         0     no  northwest   3866.85520
5    50    male  30.0         3     no  northwest  10600.54830
6    18  female  31.0         0     no  northeast   2205.98080
7    18  female  36.0         0     no  southeast   1629.83350
8    21  female  25.0         0     no  southwest   2007.94500
9    61  female  29.0         0    yes  northwest  29141.36030
10   51    male  31.0         0     no  northwest   9174.13565
11   56  female  25.0         0     no  southwest  11070.53500
12   64  female  39.0         3     no  southeast  16085.12750
13   19  female  28.0         0    yes  northwest  17468.98390
14   51  female  34.0         0     no  southeast   928

In [257]:
change_bottom = Dataset1.tail(2).rename(columns={
    'Age':'AGE',
    'Sex':'SEX',
    'Bmi':'BMI',
    'Children':'CHILDREN',
    'Smoker':'SMOKER',
    'Region':'REGION',
    'Charges':'CHARGES'
    })
change_bottom = change_bottom.reset_index(drop=True)
change_top = Dataset1.head(2)
change_top = change_top.reset_index(drop=True)
change_center = Dataset1[1001:1003].rename(columns={
    'Age':'AGE',
    'Sex':'SEX',
    'Bmi':'BMI',
    'Children':'CHILDREN',
    'Smoker':'SMOKER',
    'Region':'REGION',
})
change_center = change_center.reset_index(drop=True)
b_new_set = pd.concat([change_bottom, change_top, change_center], axis=1)
print(b_new_set)

   AGE     SEX   BMI  CHILDREN  SMOKER     REGION     CHARGES  Age     Sex  \
0   21  female  25.0         0      no  southwest   2007.9450   19  female   
1   61  female  29.0         0     yes  northwest  29141.3603   18    male   

    Bmi  ...  Smoker     Region     Charges  AGE   SEX   BMI  CHILDREN  \
0  27.0  ...     yes  southwest  16884.9240   24  male  32.0         0   
1  33.0  ...      no  southeast   1725.5523   24  male  25.0         0   

   SMOKER     REGION    Charges  
0     yes  southwest  34472.841  
1      no  southwest   1972.950  

[2 rows x 21 columns]


In [258]:
import numpy as np
randomly = np.random.rand(10,6)
for i in randomly:
    print(i)

[0.44602732 0.13906016 0.22285551 0.67395952 0.48064831 0.11218272]
[0.62542304 0.47072537 0.10650842 0.81176556 0.05996213 0.27735229]
[0.4143528  0.67043222 0.62818155 0.09024767 0.83185754 0.1466481 ]
[0.19834694 0.53685918 0.79625119 0.40910954 0.18682742 0.1930606 ]
[0.3771862  0.03983944 0.81340671 0.26799025 0.63852303 0.99276433]
[0.20991118 0.37141387 0.88025573 0.05994027 0.68450162 0.79316652]
[0.95587841 0.30365178 0.38887372 0.86681118 0.21659002 0.13638578]
[0.09826163 0.42133565 0.12362431 0.41809041 0.17089938 0.98388363]
[0.34318779 0.31716822 0.10009542 0.93609452 0.76545493 0.97699354]
[0.99160031 0.97866556 0.70622665 0.34600627 0.4641167  0.22751979]


In [259]:
import pandas as pd
import numpy as np
random_col = np.random.rand(10,6)
for i in range(random_col.shape[1]):
    nan_value = np.random.choice(5,3, replace=False)
    random_col[nan_value, i] = np.nan
    data_f = pd.DataFrame(random_col)
print(data_f)

          0         1         2         3         4         5
0       NaN       NaN  0.071680       NaN  0.554177       NaN
1  0.123551       NaN  0.671472       NaN       NaN       NaN
2       NaN  0.017741       NaN       NaN  0.477433  0.872990
3  0.388356  0.174776       NaN  0.222698       NaN       NaN
4       NaN       NaN       NaN  0.183137       NaN  0.523432
5  0.824067  0.807897  0.809777  0.222370  0.922036  0.733477
6  0.050082  0.409725  0.972862  0.093514  0.059775  0.601934
7  0.693163  0.904394  0.416228  0.291507  0.762494  0.639662
8  0.698785  0.627949  0.001669  0.099050  0.807246  0.468685
9  0.081800  0.811929  0.396249  0.415496  0.452978  0.262386


In [260]:
data_f.columns=['col1','col2','col3','col4','col5','col6']
print(data_f)

       col1      col2      col3      col4      col5      col6
0       NaN       NaN  0.071680       NaN  0.554177       NaN
1  0.123551       NaN  0.671472       NaN       NaN       NaN
2       NaN  0.017741       NaN       NaN  0.477433  0.872990
3  0.388356  0.174776       NaN  0.222698       NaN       NaN
4       NaN       NaN       NaN  0.183137       NaN  0.523432
5  0.824067  0.807897  0.809777  0.222370  0.922036  0.733477
6  0.050082  0.409725  0.972862  0.093514  0.059775  0.601934
7  0.693163  0.904394  0.416228  0.291507  0.762494  0.639662
8  0.698785  0.627949  0.001669  0.099050  0.807246  0.468685
9  0.081800  0.811929  0.396249  0.415496  0.452978  0.262386


In [261]:
individual = np.random.rand(6,3)
#print(individual)
for y in range(individual.shape[1]):
    #print(y)
    nan_indi = np.random.choice(3,2, replace=False)
    individual[nan_indi, y] = np.nan
    data_frame = pd.DataFrame(individual)
print(data_frame)


          0         1         2
0       NaN  0.554095  0.551424
1  0.716360       NaN       NaN
2       NaN       NaN       NaN
3  0.031832  0.988271  0.782672
4  0.131056  0.589050  0.760480
5  0.437897  0.149703  0.836903


In [262]:
data_frame.columns=['col1','col2','col3']
print(data_frame)

       col1      col2      col3
0       NaN  0.554095  0.551424
1  0.716360       NaN       NaN
2       NaN       NaN       NaN
3  0.031832  0.988271  0.782672
4  0.131056  0.589050  0.760480
5  0.437897  0.149703  0.836903


In [263]:
data_frame1 = data_frame.copy()
data_frame2 = data_frame.copy()
data_frame3 = data_frame.copy()
data_frame4 = data_frame.copy()
data_frame5 = data_frame.copy()
data_frame6 = data_frame.copy()
data_frame7 = data_frame.copy()
data_frame8 = data_frame.copy()

In [264]:
new_data1 = data_frame.dropna()
print(new_data1)

       col1      col2      col3
3  0.031832  0.988271  0.782672
4  0.131056  0.589050  0.760480
5  0.437897  0.149703  0.836903


In [265]:
data_frame.drop('col1', axis=1, inplace=True)
print(data_frame)

       col2      col3
0  0.554095  0.551424
1       NaN       NaN
2       NaN       NaN
3  0.988271  0.782672
4  0.589050  0.760480
5  0.149703  0.836903


In [266]:
data_frame1.drop(['col1','col2'], axis=1, inplace=True)
print(data_frame1)

       col3
0  0.551424
1       NaN
2       NaN
3  0.782672
4  0.760480
5  0.836903


In [272]:
data_frame2.fillna(6, inplace=True)
print(data_frame2)

       col1      col2      col3
0  6.000000  0.554095  0.551424
1  0.716360  6.000000  6.000000
2  6.000000  6.000000  6.000000
3  0.031832  0.988271  0.782672
4  0.131056  0.589050  0.760480
5  0.437897  0.149703  0.836903


In [278]:
data_frame3['col1'] = data_frame3['col2'].fillna(3)
print(data_frame3)

       col1      col2      col3
0  0.554095  0.554095  0.551424
1  3.000000       NaN       NaN
2  3.000000       NaN       NaN
3  0.988271  0.988271  0.782672
4  0.589050  0.589050  0.760480
5  0.149703  0.149703  0.836903


In [286]:
data_frame3['col2'] = data_frame3['col2'].fillna(data_frame3['col2'].mean())
print(data_frame3)

       col1      col2      col3
0  0.554095  0.554095  0.551424
1  3.000000  0.570280       NaN
2  3.000000  0.570280       NaN
3  0.988271  0.988271  0.782672
4  0.589050  0.589050  0.760480
5  0.149703  0.149703  0.836903


In [288]:
data_frame3['col3'] = data_frame3['col3'].fillna(data_frame3['col3'].max())
print(data_frame3)

       col1      col2      col3
0  0.554095  0.554095  0.551424
1  3.000000  0.570280  0.836903
2  3.000000  0.570280  0.836903
3  0.988271  0.988271  0.782672
4  0.589050  0.589050  0.760480
5  0.149703  0.149703  0.836903
