In [4]:
import pandas as pd
a = [3,5,7]
df = pd.Series(a)
df

0    3
1    5
2    7
dtype: int64

In [5]:
df.info()

<class 'pandas.core.series.Series'>
RangeIndex: 3 entries, 0 to 2
Series name: None
Non-Null Count  Dtype
--------------  -----
3 non-null      int64
dtypes: int64(1)
memory usage: 156.0 bytes


In [6]:
a = (3,5,7)
df = pd.Series(a)
df

0    3
1    5
2    7
dtype: int64

In [ ]:
dic = {
    'Name':['Maruf', 'Jidni'],
    'Roll': [884598, 884588]
    }
df = pd.Series(dic)
df

Name      [Maruf, Jidni]
Roll    [884598, 884588]
dtype: object

In [13]:
df.info()

<class 'pandas.core.series.Series'>
Index: 2 entries, Name to Roll
Series name: None
Non-Null Count  Dtype 
--------------  ----- 
2 non-null      object
dtypes: object(1)
memory usage: 140.0+ bytes


In [18]:
dic = {
    'Name' : ['Maruf', 'Rajin', 'Jidni'],
    'Roll' : [23, 56, 21],
    'dep' : ['cst', 'auto', 'cst']
}
df = pd.Series(dic, index=['Name', 'Roll', 'dep'])
df

Name    [Maruf, Rajin, Jidni]
Roll             [23, 56, 21]
dep          [cst, auto, cst]
dtype: object

In [19]:
df.info()

<class 'pandas.core.series.Series'>
Index: 3 entries, Name to dep
Series name: None
Non-Null Count  Dtype 
--------------  ----- 
3 non-null      object
dtypes: object(1)
memory usage: 156.0+ bytes


In [31]:
a = [[3,5,7]]
df = pd.DataFrame(a)
df


0  1  2
0  3  5  7

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       1 non-null      int64
 1   1       1 non-null      int64
 2   2       1 non-null      int64
dtypes: int64(3)
memory usage: 156.0 bytes


In [26]:
b = [3,5,7]
df2 = pd.DataFrame(b)
df2

0
0  3
1  5
2  7

In [28]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       3 non-null      int64
dtypes: int64(1)
memory usage: 156.0 bytes


In [32]:
a = [[3,5,7]]
df = pd.DataFrame(a, columns=['N1', 'N2', 'N3'])
df

N1  N2  N3
0   3   5   7

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   N1      1 non-null      int64
 1   N2      1 non-null      int64
 2   N3      1 non-null      int64
dtypes: int64(3)
memory usage: 156.0 bytes


In [38]:
b = [3,5,7]
df2 = pd.DataFrame(b, columns=['Rolls'])
df2

Rolls
0      3
1      5
2      7

In [36]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       3 non-null      int64
dtypes: int64(1)
memory usage: 156.0 bytes


In [50]:
b = [['maruf', 'jidni', 'rajin'],[3,5,7]]
df2 = pd.DataFrame(b)
df2

0      1      2
0  maruf  jidni  rajin
1      3      5      7

In [41]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       2 non-null      object
 1   1       2 non-null      object
 2   2       2 non-null      object
dtypes: object(3)
memory usage: 180.0+ bytes


In [45]:
b = [['maruf', 'jidni', 'rajin'],[3,5,7]]
df2 = pd.DataFrame(b, columns= ['col1', 'col2', 'col3'])
df2

col1   col2   col3
0  maruf  jidni  rajin
1      3      5      7

In [46]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   col1    2 non-null      object
 1   col2    2 non-null      object
 2   col3    2 non-null      object
dtypes: object(3)
memory usage: 180.0+ bytes


In [54]:
dic = {
    'Name' : ['Maruf', 'Rajin', 'Jidni', 'robin'],
    'Roll' : [23, 56, 21, 56],
    'dep' : ['cst', 'auto', 'cst', 'Et']
}
df = pd.DataFrame(dic)
df

Name  Roll   dep
0  Maruf    23   cst
1  Rajin    56  auto
2  Jidni    21   cst
3  robin    56    Et

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Roll    4 non-null      int64 
 2   dep     4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes


In [ ]:
dic = {
    'Name' : ['Maruf', 'Rajin', 'Jidni', 'robin'],
    'Roll' : [23, 56, 21, 56],
    'dep' : ['cst', 'auto', 'cst', 'Et']
}
df = pd.DataFrame(dic)
#df = pd.DataFrame(dic, columns=['NAME','ROLL', 'DEP']) don't change like this
df

Name  Roll   dep
0  Maruf    23   cst
1  Rajin    56  auto
2  Jidni    21   cst
3  robin    56    Et

In [59]:
df = df.rename({'Name':'নাম', 'Roll':'রোল', 'dep':'ডিপারট্মেন্ট'}, axis=1)
df

নাম  রোল ডিপারট্মেন্ট
0  Maruf   23          cst
1  Rajin   56         auto
2  Jidni   21          cst
3  robin   56           Et

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   নাম           4 non-null      object
 1   রোল           4 non-null      int64 
 2   ডিপারট্মেন্ট  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 128.0+ bytes


In [65]:
dic = {
    'Name' : ['Maruf', 'Rajin', 'Jidni', 'robin'],
    'Roll' : [23, 56, 21, 56],
    'dep' : ['cst', 'auto', 'cst', 'Et']
}
df = pd.DataFrame(dic)
df

Name  Roll   dep
0  Maruf    23   cst
1  Rajin    56  auto
2  Jidni    21   cst
3  robin    56    Et

In [67]:
df['Roll']

0    23
1    56
2    21
3    56
Name: Roll, dtype: int64

In [70]:
df[['Roll']]

Roll
0    23
1    56
2    21
3    56

In [71]:
df[['Name']]

Name
0  Maruf
1  Rajin
2  Jidni
3  robin

In [72]:
df[['dep']]

dep
0   cst
1  auto
2   cst
3    Et

In [74]:
dic = {
    'Name' : ['Maruf', 'Rajin', 'Jidni', 'robin'],
    'Roll' : [2354367467, 564567756, 214567567, 56567457],
    'dep' : ['cst', 'auto', 'cst', 'Et']
}
df = pd.DataFrame(dic)
df

Name        Roll   dep
0  Maruf  2354367467   cst
1  Rajin   564567756  auto
2  Jidni   214567567   cst
3  robin    56567457    Et

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Roll    4 non-null      int64 
 2   dep     4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes


In [81]:
df[['Roll']].astype('int64')

Roll
0  2354367467
1   564567756
2   214567567
3    56567457

In [83]:
df[['Roll']].astype('int32')

Roll
0 -1940599829
1   564567756
2   214567567
3    56567457

In [84]:
df[['Roll']].astype('int16')

Roll
0 -13333
1 -24884
2   2703
3   9889

In [85]:
dic = {
    'Name' : ['Maruf', 'Rajin', 'Jidni', 'robin'],
    'Roll' : [230, 560, 210, 500],
    'dep' : ['cst', 'auto', 'cst', 'Et']
}
df = pd.DataFrame(dic)
df

Name  Roll   dep
0  Maruf   230   cst
1  Rajin   560  auto
2  Jidni   210   cst
3  robin   500    Et

In [89]:
df['Roll']>300 # can't use 2 dimesional array

0    False
1     True
2    False
3     True
Name: Roll, dtype: bool

In [92]:
df[df['Roll']>300]

Name  Roll   dep
1  Rajin   560  auto
3  robin   500    Et

In [93]:
df[df['Roll']>300]['Name']

1    Rajin
3    robin
Name: Name, dtype: object

In [100]:
dic1 = {
    'Name' : ['Maruf', 'Rajin', 'Jidni', 'robin'],
    'Roll' : [230, 560, 210, 500],
    'Dep' : ['cst', 'auto', 'cst', 'Et']
}
df3 = pd.DataFrame(dic)
df3

Name  Roll   dep
0  Maruf   230   cst
1  Rajin   560  auto
2  Jidni   210   cst
3  robin   500    Et

In [101]:
dic2 = {
    'name':['nibir','alimoon','sameer','aryan'],
    'roll':[435,65,5,67],
    'dep':['mec','sc','auto','cst']

}
df4 = pd.DataFrame(dic2)
print(df4)

      name  roll   dep
0    nibir   435   mec
1  alimoon    65    sc
2   sameer     5  auto
3    aryan    67   cst


In [104]:
new_dic = pd.concat([df3,df4])
print(new_dic)

    Name   Roll   dep     name   roll
0  Maruf  230.0   cst      NaN    NaN
1  Rajin  560.0  auto      NaN    NaN
2  Jidni  210.0   cst      NaN    NaN
3  robin  500.0    Et      NaN    NaN
0    NaN    NaN   mec    nibir  435.0
1    NaN    NaN    sc  alimoon   65.0
2    NaN    NaN  auto   sameer    5.0
3    NaN    NaN   cst    aryan   67.0


In [106]:
new_dic = pd.concat([df3,df4], axis=1)
print(new_dic)

    Name  Roll   dep     name  roll   dep
0  Maruf   230   cst    nibir   435   mec
1  Rajin   560  auto  alimoon    65    sc
2  Jidni   210   cst   sameer     5  auto
3  robin   500    Et    aryan    67   cst


In [115]:
dic1 = {
    'Name' : ['Maruf', 'Rajin', 'Jidni', 'robin'],
    'Roll' : [230, 560, 210, 500],
    'Dep' : ['cst', 'auto', 'cst', 'Et']
}
df3 = pd.DataFrame(dic1)
df3

Name  Roll   Dep
0  Maruf   230   cst
1  Rajin   560  auto
2  Jidni   210   cst
3  robin   500    Et

In [113]:
dic2 = {
    'Name':['nibir','alimoon','sameer','aryan'],
    'Roll':[435,65,5,67],
    'Dep':['mec','sc','auto','cst']

}
df4 = pd.DataFrame(dic2)
print(df4)

      Name  Roll   Dep
0    nibir   435   mec
1  alimoon    65    sc
2   sameer     5  auto
3    aryan    67   cst


In [116]:
new_dic2 = pd.concat([df3,df4])
print(new_dic2)

      Name  Roll   Dep
0    Maruf   230   cst
1    Rajin   560  auto
2    Jidni   210   cst
3    robin   500    Et
0    nibir   435   mec
1  alimoon    65    sc
2   sameer     5  auto
3    aryan    67   cst


In [117]:
new_dic2 = pd.concat([df3,df4], ignore_index=True)
print(new_dic2)

      Name  Roll   Dep
0    Maruf   230   cst
1    Rajin   560  auto
2    Jidni   210   cst
3    robin   500    Et
4    nibir   435   mec
5  alimoon    65    sc
6   sameer     5  auto
7    aryan    67   cst


In [120]:
import numpy as np
data = np.random.rand(10,5)
print(data)

[[0.30811919 0.99285116 0.95646887 0.10477275 0.04463709]
 [0.66866681 0.29413653 0.35907449 0.82600087 0.39645553]
 [0.43154484 0.2176686  0.88444627 0.93482596 0.31577976]
 [0.35434311 0.62279777 0.69762564 0.97737693 0.37674516]
 [0.65921608 0.57315556 0.91229736 0.965634   0.24095254]
 [0.95280931 0.20968364 0.1031416  0.65845113 0.83746602]
 [0.55379773 0.29120523 0.37644402 0.18026444 0.9138162 ]
 [0.98363647 0.85834018 0.01013491 0.96513293 0.01705273]
 [0.65020876 0.22145084 0.90288327 0.59503862 0.03656721]
 [0.69473499 0.37668486 0.93874492 0.98983777 0.8826212 ]]


In [122]:
data = np.random.rand(10,5)
for x in data:
    print(x)

[0.2329046  0.71164058 0.89737341 0.14272985 0.56484852]
[0.08775462 0.27958273 0.46572533 0.9236855  0.03108869]
[0.99332306 0.96198944 0.32614333 0.65132847 0.91414647]
[0.35936406 0.26440382 0.34143749 0.43563402 0.46677923]
[0.48164564 0.10469323 0.61356482 0.75659758 0.80419393]
[0.04498866 0.93655952 0.39461489 0.06648538 0.62272337]
[0.88715298 0.78140119 0.14341764 0.06175053 0.15984595]
[0.2242978  0.17251653 0.23095747 0.25088656 0.12205014]
[0.87966799 0.71068088 0.25450018 0.03529956 0.16338991]
[0.22061589 0.215305   0.56587393 0.03328683 0.71296935]


In [123]:
data = np.random.rand(10,5)
for x in range(data):
    print(x)

TypeError: only integer scalar arrays can be converted to a scalar index